<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */


declare(strict_types=1);

namespace ReThink\BridgeSDK\Hooks;

use ReThink\BridgeSDK\SDKConfiguration;

interface SDKInitHook
{
    public function sdkInit(SDKConfiguration $config): SDKConfiguration;
}
