workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Bridge API:
        inputs:
            - location: openapi.json
        overlays:
            - location: .speakeasy\speakeasy-modifications-overlay.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/rethink/bridge/bridge-api
targets:
    bridge-sdk:
        target: php
        source: Bridge API
        publish:
            packagist:
                username: $packagist_username
                token: $packagist_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/rethink/bridge/bridge-api-php-code-samples
            labelOverride:
                fixedValue: Php (SDK)
            blocking: false
