<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Operations;

use ReThink\BridgeSDK\Models\Components;
/** GetCustomersCustomerIDLiquidationAddressesLiquidationAddresses - List of Liquidation Addresses (the returned list is empty if none found) */
class GetCustomersCustomerIDLiquidationAddressesLiquidationAddresses
{
    /**
     * total number of items in data
     *
     * @var int $count
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('count')]
    public int $count;

    /**
     * $data
     *
     * @var array<Components\LiquidationAddress> $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\ReThink\BridgeSDK\Models\Components\LiquidationAddress>')]
    public array $data;

    /**
     * @param  int  $count
     * @param  array<Components\LiquidationAddress>  $data
     * @phpstan-pure
     */
    public function __construct(int $count, array $data)
    {
        $this->count = $count;
        $this->data = $data;
    }
}