<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Operations;

use ReThink\BridgeSDK\Models\Components;
/** GetCustomersCustomerIDVirtualAccountsVirtualAccountIDHistoryVirtualAccountHistory - List of Virtual Account events */
class GetCustomersCustomerIDVirtualAccountsVirtualAccountIDHistoryVirtualAccountHistory
{
    /**
     * The number of events returned
     *
     * @var int $count
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('count')]
    public int $count;

    /**
     * $data
     *
     * @var array<Components\VirtualAccountEvent> $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\ReThink\BridgeSDK\Models\Components\VirtualAccountEvent>')]
    public array $data;

    /**
     * @param  int  $count
     * @param  array<Components\VirtualAccountEvent>  $data
     * @phpstan-pure
     */
    public function __construct(int $count, array $data)
    {
        $this->count = $count;
        $this->data = $data;
    }
}