<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Operations;

use ReThink\BridgeSDK\Models\Components;
use ReThink\BridgeSDK\Utils\SpeakeasyMetadata;
class GetCustomersCustomerIDCardAccountsCardAccountIDAuthorizationsRequest
{
    /**
     *
     * @var string $customerID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=customerID')]
    public string $customerID;

    /**
     *
     * @var string $cardAccountID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=cardAccountID')]
    public string $cardAccountID;

    /**
     * The number of pending card authorizations to return, with a max of 200. The default is 100
     *
     * @var ?int $limit
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?int $limit = null;

    /**
     * The starting time in ISO8601 format. Default is 50 days ago.
     *
     * @var ?string $startingTime
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=starting_time')]
    public ?string $startingTime = null;

    /**
     * The exclusive ending time in ISO8601 format. Default is now.
     *
     * @var ?string $endingTime
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=ending_time')]
    public ?string $endingTime = null;

    /**
     * A status to filter the authorizations by. If not provided, will default to `approved`.
     *
     * @var ?Components\CardAuthorizationStatusParameter $status
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=status')]
    public ?Components\CardAuthorizationStatusParameter $status = null;

    /**
     * @param  string  $customerID
     * @param  string  $cardAccountID
     * @param  ?int  $limit
     * @param  ?string  $startingTime
     * @param  ?string  $endingTime
     * @param  ?Components\CardAuthorizationStatusParameter  $status
     * @phpstan-pure
     */
    public function __construct(string $customerID, string $cardAccountID, ?int $limit = null, ?string $startingTime = null, ?string $endingTime = null, ?Components\CardAuthorizationStatusParameter $status = null)
    {
        $this->customerID = $customerID;
        $this->cardAccountID = $cardAccountID;
        $this->limit = $limit;
        $this->startingTime = $startingTime;
        $this->endingTime = $endingTime;
        $this->status = $status;
    }
}