<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Operations;

use ReThink\BridgeSDK\Models\Components;
use ReThink\BridgeSDK\Utils\SpeakeasyMetadata;
class GetCustomersCustomerIDKycLinkRequest
{
    /**
     *
     * @var string $customerID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=customerID')]
    public string $customerID;

    /**
     * An endorsement is the approval required for a customer to use a particular product or service offered by Bridge
     *
     * @var ?Components\EndorsementParameter $endorsement
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=endorsement')]
    public ?Components\EndorsementParameter $endorsement = null;

    /**
     * An optional url encoded link that users will be redirected to after completing the hosted KYC flow.
     *
     * @var ?string $redirectUri
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=redirect_uri')]
    public ?string $redirectUri = null;

    /**
     * @param  string  $customerID
     * @param  ?Components\EndorsementParameter  $endorsement
     * @param  ?string  $redirectUri
     * @phpstan-pure
     */
    public function __construct(string $customerID, ?Components\EndorsementParameter $endorsement = null, ?string $redirectUri = null)
    {
        $this->customerID = $customerID;
        $this->endorsement = $endorsement;
        $this->redirectUri = $redirectUri;
    }
}