<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Operations;

use ReThink\BridgeSDK\Utils\SpeakeasyMetadata;
class GetExchangeRatesRequest
{
    /**
     * The currency code to convert from.
     *
     * @var FromT $from
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=from')]
    public FromT $from;

    /**
     * The currency code to convert to.
     *
     * @var To $to
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=to')]
    public To $to;

    /**
     * @param  FromT  $from
     * @param  To  $to
     * @phpstan-pure
     */
    public function __construct(FromT $from, To $to)
    {
        $this->from = $from;
        $this->to = $to;
    }
}