<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Operations;

use ReThink\BridgeSDK\Utils\SpeakeasyMetadata;
class GetPrefundedAccountsPrefundedAccountIDHistoryRequest
{
    /**
     *
     * @var string $prefundedAccountID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=prefundedAccountID')]
    public string $prefundedAccountID;

    /**
     * The number of items to return (default of 10, max of 100)
     *
     * @var ?int $limit
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?int $limit = null;

    /**
     * This is a prefunded event id. If this is specified, the next page that starts with an event right AFTER the specified event id on the event timeline, which is always ordered from the newest to the oldest by creation time, will be returned. This also implies that events older than the specified event id will be returned (shouldn't be set if ending_before is set)
     *
     * @var ?string $startingAfter
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=starting_after')]
    public ?string $startingAfter = null;

    /**
     * This is a prefunded event id. If this is specified, the previous page that ends with an event right BEFORE the specified event id on the event timeline, which is always ordered from the newest to the oldest by creation time, will be returned. This also implies that events newer than the specified event id will be returned (shouldn't be set if starting_after is set)
     *
     * @var ?string $endingBefore
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=ending_before')]
    public ?string $endingBefore = null;

    /**
     * @param  string  $prefundedAccountID
     * @param  ?int  $limit
     * @param  ?string  $startingAfter
     * @param  ?string  $endingBefore
     * @phpstan-pure
     */
    public function __construct(string $prefundedAccountID, ?int $limit = null, ?string $startingAfter = null, ?string $endingBefore = null)
    {
        $this->prefundedAccountID = $prefundedAccountID;
        $this->limit = $limit;
        $this->startingAfter = $startingAfter;
        $this->endingBefore = $endingBefore;
    }
}