<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Operations;

use ReThink\BridgeSDK\Models\Components;
use ReThink\BridgeSDK\Utils\SpeakeasyMetadata;
class GetStaticMemosHistoryRequest
{
    /**
     * The deposit id associated with the events. Cannot be passed if deposit_ids is also passed
     *
     * @var ?string $depositId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=deposit_id')]
    public ?string $depositId = null;

    /**
     * The deposit ids associated with the events. Pass a list of deposit ids like "deposit_ids[]=id1&deposit_ids[]=id2". Cannot be passed if deposit_id is also passed
     *
     * @var ?array<string> $depositIds
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=deposit_ids')]
    public ?array $depositIds = null;

    /**
     * The hash of the transaction
     *
     * @var ?string $txHash
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=tx_hash')]
    public ?string $txHash = null;

    /**
     * The number of items to return (default of 10, max of 100)
     *
     * @var ?int $limit
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?int $limit = null;

    /**
     * This is an event id. If this is specified, the next page that starts with an event right AFTER the specified event id on the event timeline, which is always ordered from the newest to the oldest by creation time, will be returned. This also implies that events older than the specified event id will be returned (shouldn't be set if ending_before is set)
     *
     * @var ?string $startingAfter
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=starting_after')]
    public ?string $startingAfter = null;

    /**
     * This is an event id. If this is specified, the previous page that ends with an event right BEFORE the specified event id on the event timeline, which is always ordered from the newest to the oldest by creation time, will be returned. This also implies that events newer than the specified event id will be returned (shouldn't be set if starting_after is set)
     *
     * @var ?string $endingBefore
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=ending_before')]
    public ?string $endingBefore = null;

    /**
     * Filter history by event type
     *
     * @var ?Components\EventTypeParameter $eventType
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=event_type')]
    public ?Components\EventTypeParameter $eventType = null;

    /**
     * @param  ?string  $depositId
     * @param  ?array<string>  $depositIds
     * @param  ?string  $txHash
     * @param  ?int  $limit
     * @param  ?string  $startingAfter
     * @param  ?string  $endingBefore
     * @param  ?Components\EventTypeParameter  $eventType
     * @phpstan-pure
     */
    public function __construct(?string $depositId = null, ?array $depositIds = null, ?string $txHash = null, ?int $limit = null, ?string $startingAfter = null, ?string $endingBefore = null, ?Components\EventTypeParameter $eventType = null)
    {
        $this->depositId = $depositId;
        $this->depositIds = $depositIds;
        $this->txHash = $txHash;
        $this->limit = $limit;
        $this->startingAfter = $startingAfter;
        $this->endingBefore = $endingBefore;
        $this->eventType = $eventType;
    }
}