<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Operations;

use ReThink\BridgeSDK\Models\Components;
/** GetTransfersStaticTemplatesStaticTemplates - List of static templates (the returned list is empty if none found). Static templates are transfers that are used as templates for other transfers and can be created using the static_templates feature flag. */
class GetTransfersStaticTemplatesStaticTemplates
{
    /**
     * The number of static templates returned
     *
     * @var int $count
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('count')]
    public int $count;

    /**
     * $data
     *
     * @var array<Components\TransferResponse> $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\ReThink\BridgeSDK\Models\Components\TransferResponse>')]
    public array $data;

    /**
     * @param  int  $count
     * @param  array<Components\TransferResponse>  $data
     * @phpstan-pure
     */
    public function __construct(int $count, array $data)
    {
        $this->count = $count;
        $this->data = $data;
    }
}