<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Operations;

use ReThink\BridgeSDK\Models\Components;
use ReThink\BridgeSDK\Utils\SpeakeasyMetadata;
class PostKycLinksRequest
{
    /**
     *
     * @var string $idempotencyKey
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=Idempotency-Key')]
    public string $idempotencyKey;

    /**
     * Information about the customer to create KYC Links for
     *
     * @var Components\CreateKycLinks $body
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\CreateKycLinks $body;

    /**
     * @param  string  $idempotencyKey
     * @param  Components\CreateKycLinks  $body
     * @phpstan-pure
     */
    public function __construct(string $idempotencyKey, Components\CreateKycLinks $body)
    {
        $this->idempotencyKey = $idempotencyKey;
        $this->body = $body;
    }
}