<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Operations;

use ReThink\BridgeSDK\Models\Components;
use ReThink\BridgeSDK\Utils\SpeakeasyMetadata;
class PostDeveloperFeesRequest
{
    /**
     *
     * @var string $idempotencyKey
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=Idempotency-Key')]
    public string $idempotencyKey;

    /**
     * The default fee percent that will be applied to all your Liquidation Addresses. The value is a base 100 percentage, i.e. 10.2% is 10.2 in the API.
     *
     * @var Components\DeveloperFees $body
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\DeveloperFees $body;

    /**
     * @param  string  $idempotencyKey
     * @param  Components\DeveloperFees  $body
     * @phpstan-pure
     */
    public function __construct(string $idempotencyKey, Components\DeveloperFees $body)
    {
        $this->idempotencyKey = $idempotencyKey;
        $this->body = $body;
    }
}