<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Operations;

use ReThink\BridgeSDK\Models\Components;
use ReThink\BridgeSDK\Utils\SpeakeasyMetadata;
class PostDeveloperFeeExternalAccountRequest
{
    /**
     *
     * @var string $idempotencyKey
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=Idempotency-Key')]
    public string $idempotencyKey;

    /**
     * New External Account object to be created
     *
     * @var Components\CreateFeeExternalAccountInputACHWire|Components\CreateFeeExternalAccountInputIBAN|Components\CreateFeeExternalAccountInputSWIFT|Components\CreateFeeExternalAccountInputCLABE|Components\CreateFeeExternalAccountInputPixPixKey|Components\CreateFeeExternalAccountInputPixBRCode|Components\CreateFeeExternalAccountInputFPSBeta $body
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\CreateFeeExternalAccountInputACHWire|Components\CreateFeeExternalAccountInputIBAN|Components\CreateFeeExternalAccountInputSWIFT|Components\CreateFeeExternalAccountInputCLABE|Components\CreateFeeExternalAccountInputPixPixKey|Components\CreateFeeExternalAccountInputPixBRCode|Components\CreateFeeExternalAccountInputFPSBeta $body;

    /**
     * @param  string  $idempotencyKey
     * @param  Components\CreateFeeExternalAccountInputACHWire|Components\CreateFeeExternalAccountInputIBAN|Components\CreateFeeExternalAccountInputSWIFT|Components\CreateFeeExternalAccountInputCLABE|Components\CreateFeeExternalAccountInputPixPixKey|Components\CreateFeeExternalAccountInputPixBRCode|Components\CreateFeeExternalAccountInputFPSBeta  $body
     * @phpstan-pure
     */
    public function __construct(string $idempotencyKey, Components\CreateFeeExternalAccountInputACHWire|Components\CreateFeeExternalAccountInputIBAN|Components\CreateFeeExternalAccountInputSWIFT|Components\CreateFeeExternalAccountInputCLABE|Components\CreateFeeExternalAccountInputPixPixKey|Components\CreateFeeExternalAccountInputPixBRCode|Components\CreateFeeExternalAccountInputFPSBeta $body)
    {
        $this->idempotencyKey = $idempotencyKey;
        $this->body = $body;
    }
}