<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Operations;

use ReThink\BridgeSDK\Utils\SpeakeasyMetadata;
class PostCustomersCustomerIDExternalAccountsExternalAccountIDReactivateRequest
{
    /**
     *
     * @var string $idempotencyKey
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=Idempotency-Key')]
    public string $idempotencyKey;

    /**
     *
     * @var string $customerID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=customerID')]
    public string $customerID;

    /**
     *
     * @var string $externalAccountID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=externalAccountID')]
    public string $externalAccountID;

    /**
     * @param  string  $idempotencyKey
     * @param  string  $customerID
     * @param  string  $externalAccountID
     * @phpstan-pure
     */
    public function __construct(string $idempotencyKey, string $customerID, string $externalAccountID)
    {
        $this->idempotencyKey = $idempotencyKey;
        $this->customerID = $customerID;
        $this->externalAccountID = $externalAccountID;
    }
}