<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Operations;

use ReThink\BridgeSDK\Models\Components;
use ReThink\BridgeSDK\Utils\SpeakeasyMetadata;
class PostCustomersCustomerIDCardAccountsCardAccountIDEphemeralKeysRequest
{
    /**
     *
     * @var string $customerID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=customerID')]
    public string $customerID;

    /**
     *
     * @var string $idempotencyKey
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=Idempotency-Key')]
    public string $idempotencyKey;

    /**
     * The ID of the card account
     *
     * @var string $cardAccountID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=cardAccountID')]
    public string $cardAccountID;

    /**
     * The client-side nonce that will be associated with the ephemeral key
     *
     * @var ?Components\PostCardAccountEphemeralKeyInput $body
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?Components\PostCardAccountEphemeralKeyInput $body = null;

    /**
     * @param  string  $customerID
     * @param  string  $idempotencyKey
     * @param  string  $cardAccountID
     * @param  ?Components\PostCardAccountEphemeralKeyInput  $body
     * @phpstan-pure
     */
    public function __construct(string $customerID, string $idempotencyKey, string $cardAccountID, ?Components\PostCardAccountEphemeralKeyInput $body = null)
    {
        $this->customerID = $customerID;
        $this->idempotencyKey = $idempotencyKey;
        $this->cardAccountID = $cardAccountID;
        $this->body = $body;
    }
}