<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Operations;

use ReThink\BridgeSDK\Models\Components;
/** PostCustomersCustomerIDVirtualAccountsVirtualAccountIDDeactivateResponseBody - Deactivated Virtual Account object */
class PostCustomersCustomerIDVirtualAccountsVirtualAccountIDDeactivateResponseBody
{
    /**
     * A UUID that uniquely identifies a resource
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     *
     * @var mixed $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('mixed')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public mixed $status = null;

    /**
     * The developer fee percent that will be applied to this Virtual Account. The value is a base 100 percentage, i.e. 10.2% is 10.2 in the API.
     *
     * @var ?string $developerFeePercent
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('developer_fee_percent')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $developerFeePercent = null;

    /**
     * A UUID that uniquely identifies a resource
     *
     * @var ?string $customerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customer_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $customerId = null;

    /**
     * Time of creation of the virtual account
     *
     * @var ?\DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdAt = null;

    /**
     *
     * @var Components\VirtualAccountUS|Components\VirtualIBAN|Components\VirtualAccountMX|Components\VirtualAccountBR|Components\VirtualAccountUK|null $sourceDepositInstructions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_deposit_instructions')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\VirtualAccountUS|\ReThink\BridgeSDK\Models\Components\VirtualIBAN|\ReThink\BridgeSDK\Models\Components\VirtualAccountMX|\ReThink\BridgeSDK\Models\Components\VirtualAccountBR|\ReThink\BridgeSDK\Models\Components\VirtualAccountUK|null')]
    #[\Speakeasy\Serializer\Annotation\UnionDiscriminator(field: 'currency', map: ['usd' => '\ReThink\BridgeSDK\Models\Components\VirtualAccountUS', 'eur' => '\ReThink\BridgeSDK\Models\Components\VirtualIBAN', 'mxn' => '\ReThink\BridgeSDK\Models\Components\VirtualAccountMX', 'brl' => '\ReThink\BridgeSDK\Models\Components\VirtualAccountBR', 'gbp' => '\ReThink\BridgeSDK\Models\Components\VirtualAccountUK'])]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public Components\VirtualAccountUS|Components\VirtualIBAN|Components\VirtualAccountMX|Components\VirtualAccountBR|Components\VirtualAccountUK|null $sourceDepositInstructions = null;

    /**
     *
     * @var ?Components\VirtualAccountDestination $destination
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('destination')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\VirtualAccountDestination|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Components\VirtualAccountDestination $destination = null;

    /**
     * @param  ?string  $id
     * @param  mixed  $status
     * @param  ?string  $developerFeePercent
     * @param  ?string  $customerId
     * @param  ?\DateTime  $createdAt
     * @param  Components\VirtualAccountUS|Components\VirtualIBAN|Components\VirtualAccountMX|Components\VirtualAccountBR|Components\VirtualAccountUK|null  $sourceDepositInstructions
     * @param  ?Components\VirtualAccountDestination  $destination
     * @phpstan-pure
     */
    public function __construct(?string $id = null, mixed $status = null, ?string $developerFeePercent = null, ?string $customerId = null, ?\DateTime $createdAt = null, Components\VirtualAccountUS|Components\VirtualIBAN|Components\VirtualAccountMX|Components\VirtualAccountBR|Components\VirtualAccountUK|null $sourceDepositInstructions = null, ?Components\VirtualAccountDestination $destination = null)
    {
        $this->id = $id;
        $this->status = $status;
        $this->developerFeePercent = $developerFeePercent;
        $this->customerId = $customerId;
        $this->createdAt = $createdAt;
        $this->sourceDepositInstructions = $sourceDepositInstructions;
        $this->destination = $destination;
    }
}