<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Operations;

use ReThink\BridgeSDK\Models\Components;
use ReThink\BridgeSDK\Utils\SpeakeasyMetadata;
class PostCustomersCustomerIDWalletsRequest
{
    /**
     *
     * @var string $customerID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=customerID')]
    public string $customerID;

    /**
     *
     * @var string $idempotencyKey
     */
    #[SpeakeasyMetadata('header:style=simple,explode=false,name=Idempotency-Key')]
    public string $idempotencyKey;

    /**
     * Bridge Wallet to be created
     *
     * @var Components\CreateBridgeWallet $body
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\CreateBridgeWallet $body;

    /**
     * @param  string  $customerID
     * @param  string  $idempotencyKey
     * @param  Components\CreateBridgeWallet  $body
     * @phpstan-pure
     */
    public function __construct(string $customerID, string $idempotencyKey, Components\CreateBridgeWallet $body)
    {
        $this->customerID = $customerID;
        $this->idempotencyKey = $idempotencyKey;
        $this->body = $body;
    }
}