<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Operations;

use ReThink\BridgeSDK\Models\Components;
use ReThink\BridgeSDK\Utils\SpeakeasyMetadata;
class PutWebhooksWebhookIDRequest
{
    /**
     *
     * @var string $webhookID
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=webhookID')]
    public string $webhookID;

    /**
     * Updated webhook endpoint object
     *
     * @var Components\PutWebhookPayload $body
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\PutWebhookPayload $body;

    /**
     * @param  string  $webhookID
     * @param  Components\PutWebhookPayload  $body
     * @phpstan-pure
     */
    public function __construct(string $webhookID, Components\PutWebhookPayload $body)
    {
        $this->webhookID = $webhookID;
        $this->body = $body;
    }
}