<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


class Address2025WinterRefresh
{
    /**
     *
     * @var string $streetLine1
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('street_line_1')]
    public string $streetLine1;

    /**
     *
     * @var string $city
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('city')]
    public string $city;

    /**
     * Three-letter alpha-3 country code as defined in the ISO 3166-1 spec.
     *
     * @var string $country
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('country')]
    public string $country;

    /**
     *
     * @var ?string $streetLine2
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('street_line_2')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $streetLine2 = null;

    /**
     * ISO 3166-2 subdivision code. Must be supplied for US addresses.
     *
     * @var ?string $subdivision
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subdivision')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $subdivision = null;

    /**
     * Must be supplied for countries that use postal codes.
     *
     * @var ?string $postalCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('postal_code')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $postalCode = null;

    /**
     * @param  string  $streetLine1
     * @param  string  $city
     * @param  string  $country
     * @param  ?string  $streetLine2
     * @param  ?string  $subdivision
     * @param  ?string  $postalCode
     * @phpstan-pure
     */
    public function __construct(string $streetLine1, string $city, string $country, ?string $streetLine2 = null, ?string $subdivision = null, ?string $postalCode = null)
    {
        $this->streetLine1 = $streetLine1;
        $this->city = $city;
        $this->country = $country;
        $this->streetLine2 = $streetLine2;
        $this->subdivision = $subdivision;
        $this->postalCode = $postalCode;
    }
}