<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


class AssociatedPersonResponse
{
    /**
     * Unique identifier for the associated person
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Created timestamp in milliseconds since Unix epoch
     *
     * @var int $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    public int $createdAt;

    /**
     * Last updated timestamp in milliseconds since Unix epoch
     *
     * @var int $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updated_at')]
    public int $updatedAt;

    /**
     * The email address of the associated person
     *
     * @var ?string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $email = null;

    /**
     * The first name of the associated person
     *
     * @var ?string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('first_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $firstName = null;

    /**
     * The last name of the associated person
     *
     * @var ?string $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('last_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $lastName = null;

    /**
     * True if this person has at least 25% ownership of the business.
     *
     * @var ?bool $hasOwnership
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('has_ownership')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $hasOwnership = null;

    /**
     * True if this is the control person of the company, having significant responsibility to control, manage or influence the activities of the business entity.
     *
     * @var ?bool $hasControl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('has_control')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $hasControl = null;

    /**
     * True if this person is able to authorize transactions on behalf of the business.
     *
     * @var ?bool $isSigner
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('is_signer')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $isSigner = null;

    /**
     * The title of this associated person at the company, e.g. CEO, CFO, etc.
     *
     * @var ?string $title
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('title')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $title = null;

    /**
     * When this individual attested to the correctness of the ownership structure provided to Bridge. If provided by at least one control person, ownership documents for the business are not required.
     *
     * @var ?string $attestedOwnershipStructureAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('attested_ownership_structure_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $attestedOwnershipStructureAt = null;

    /**
     * When the associated person relationship was established in format yyyy-mm-dd.
     *
     * @var ?string $relationshipEstablishedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('relationship_established_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $relationshipEstablishedAt = null;

    /**
     * @param  string  $id
     * @param  int  $createdAt
     * @param  int  $updatedAt
     * @param  ?string  $email
     * @param  ?string  $firstName
     * @param  ?string  $lastName
     * @param  ?bool  $hasOwnership
     * @param  ?bool  $hasControl
     * @param  ?bool  $isSigner
     * @param  ?string  $title
     * @param  ?string  $attestedOwnershipStructureAt
     * @param  ?string  $relationshipEstablishedAt
     * @phpstan-pure
     */
    public function __construct(string $id, int $createdAt, int $updatedAt, ?string $email = null, ?string $firstName = null, ?string $lastName = null, ?bool $hasOwnership = null, ?bool $hasControl = null, ?bool $isSigner = null, ?string $title = null, ?string $attestedOwnershipStructureAt = null, ?string $relationshipEstablishedAt = null)
    {
        $this->id = $id;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->email = $email;
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->hasOwnership = $hasOwnership;
        $this->hasControl = $hasControl;
        $this->isSigner = $isSigner;
        $this->title = $title;
        $this->attestedOwnershipStructureAt = $attestedOwnershipStructureAt;
        $this->relationshipEstablishedAt = $relationshipEstablishedAt;
    }
}