<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


enum BankAccountOwnerType: string
{
    case Individual = 'individual';
    case Business = 'business';
}
