<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


class BridgeWalletHistorySource
{
    /**
     *
     * @var ?PaymentRail $paymentRail
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('payment_rail')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\PaymentRail|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PaymentRail $paymentRail = null;

    /**
     *
     * @var ?Currency $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\Currency|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Currency $currency = null;

    /**
     * @param  ?PaymentRail  $paymentRail
     * @param  ?Currency  $currency
     * @phpstan-pure
     */
    public function __construct(?PaymentRail $paymentRail = null, ?Currency $currency = null)
    {
        $this->paymentRail = $paymentRail;
        $this->currency = $currency;
    }
}