<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


/** Brl - Payment rail configuration for BRL */
class Brl
{
    /**
     * The payout method to use for BRL PIX transfers
     *
     * @var ?PixEnum $pix
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pix')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\PixEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PixEnum $pix = null;

    /**
     * @param  ?PixEnum  $pix
     * @phpstan-pure
     */
    public function __construct(?PixEnum $pix = null)
    {
        $this->pix = $pix;
    }
}