<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


enum BusinessDocumentsPurpose: string
{
    case AmlComfortLetter = 'aml_comfort_letter';
    case BusinessFormation = 'business_formation';
    case DirectorsRegistry = 'directors_registry';
    case ESignatureCertificate = 'e_signature_certificate';
    case EvidenceOfGoodStanding = 'evidence_of_good_standing';
    case FlowOfFunds = 'flow_of_funds';
    case MarketingMaterials = 'marketing_materials';
    case OwnershipChart = 'ownership_chart';
    case OwnershipInformation = 'ownership_information';
    case ProofOfAccountPurpose = 'proof_of_account_purpose';
    case ProofOfAddress = 'proof_of_address';
    case ProofOfEntityNameChange = 'proof_of_entity_name_change';
    case ProofOfNatureOfBusiness = 'proof_of_nature_of_business';
    case ProofOfSignatoryAuthority = 'proof_of_signatory_authority';
    case ProofOfSourceOfFunds = 'proof_of_source_of_funds';
    case ProofOfSourceOfWealth = 'proof_of_source_of_wealth';
    case ProofOfTaxIdentification = 'proof_of_tax_identification';
    case ShareholderRegister = 'shareholder_register';
    case Other = 'other';
}
