<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


class BusinessDocuments
{
    /**
     * A list of purposes that the given document serves. Click "ADD STRING" to see common document purposes for businesses, or view the full list of possible values [here](https://apidocs.bridge.xyz/docs/supported-documents).
     *
     *
     * `business_formation` and `ownership_information` documents are required for businesses.
     *
     *
     * @var array<BusinessDocumentsPurpose> $purposes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('purposes')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\ReThink\BridgeSDK\Models\Components\BusinessDocumentsPurpose>')]
    public array $purposes;

    /**
     * Base64 encoded image of the provided document, following the data-uri scheme i.e. data:image/[type];base64,[base_64_encoded_file_contents], with a minimum size of 200px x 200px 
     *
     *
     * *Maximum File Size: 24MB
     *
     * *Valid file types: .pdf, .jpeg, .jpg, .png, .heic, .tif
     *
     * @var string $file
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('file')]
    public string $file;

    /**
     * A description describing the provided document. This field is required when `other` is provided as one of the purposes.
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     * @param  array<BusinessDocumentsPurpose>  $purposes
     * @param  string  $file
     * @param  ?string  $description
     * @phpstan-pure
     */
    public function __construct(array $purposes, string $file, ?string $description = null)
    {
        $this->purposes = $purposes;
        $this->file = $file;
        $this->description = $description;
    }
}