<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


/** CardholderName - The name of the cardholder associated to the card. By default, this will be the name of the associated customer. To override the cardholder name, you can contact Bridge support. */
class CardholderName
{
    /**
     *
     * @var string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('first_name')]
    public string $firstName;

    /**
     *
     * @var string $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('last_name')]
    public string $lastName;

    /**
     *
     * @var ?string $middleName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('middle_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $middleName = null;

    /**
     * @param  string  $firstName
     * @param  string  $lastName
     * @param  ?string  $middleName
     * @phpstan-pure
     */
    public function __construct(string $firstName, string $lastName, ?string $middleName = null)
    {
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->middleName = $middleName;
    }
}