<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


/** CardTransaction - A posted transaction */
class CardTransaction
{
    /**
     * A UUID that uniquely identifies a resource
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * The category of the transaction
     *
     * @var Category $category
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('category')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\Category')]
    public Category $category;

    /**
     * The amount represented as a decimal string
     *
     * @var string $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    public string $amount;

    /**
     * The currency of the transaction
     *
     * @var CardTransactionCurrency $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\CardTransactionCurrency')]
    public CardTransactionCurrency $currency;

    /**
     * The transaction description. It includes the merchant's name and location information for card transactions
     *
     * @var string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public string $description;

    /**
     * Timestamp when the transaction was posted, in ISO8601 format
     *
     * @var string $postedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('posted_at')]
    public string $postedAt;

    /**
     * A UUID that uniquely identifies a resource
     *
     * @var ?string $cardAccountId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('card_account_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $cardAccountId = null;

    /**
     * A UUID that uniquely identifies a resource
     *
     * @var ?string $customerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customer_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $customerId = null;

    /**
     * The billing amount, represented as a decimal string. The billing amount is the amount of the transaction excluding any additional hold. This amount should be present on all purchases, but will only differ from the amount field for some merchant categories in which an upcharge is involved (e.g. gas stations, hotels).
     *
     * @var ?string $billingAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billing_amount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $billingAmount = null;

    /**
     * The merchant category code, if applicable (e.g., '5712'). Always returned for transactions with category `purchase` or `refund`
     *
     * @var ?string $merchantCategoryCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('merchant_category_code')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $merchantCategoryCode = null;

    /**
     * The merchant name, if applicable. Always returned for transactions with category `purchase` or `refund`
     *
     * @var ?string $merchantName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('merchant_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $merchantName = null;

    /**
     * The merchant location, if applicable. Always returned for transactions with category `purchase` or `refund`
     *
     * @var ?string $merchantLocation
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('merchant_location')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $merchantLocation = null;

    /**
     * Details of a transaction processed in a local currency other than USD, with currency conversion applied
     *
     * @var ?CardLocalTransactionDetails $localTransactionDetails
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('local_transaction_details')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\CardLocalTransactionDetails|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CardLocalTransactionDetails $localTransactionDetails = null;

    /**
     * Timestamp when the transaction was authorized, in ISO8601 format. Applicable only to transactions with category `purchase` or `refund` and always returned when applicable
     *
     * @var ?string $authorizedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('authorized_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $authorizedAt = null;

    /**
     * @param  string  $id
     * @param  Category  $category
     * @param  string  $amount
     * @param  CardTransactionCurrency  $currency
     * @param  string  $description
     * @param  string  $postedAt
     * @param  ?string  $cardAccountId
     * @param  ?string  $customerId
     * @param  ?string  $billingAmount
     * @param  ?string  $merchantCategoryCode
     * @param  ?string  $merchantName
     * @param  ?string  $merchantLocation
     * @param  ?CardLocalTransactionDetails  $localTransactionDetails
     * @param  ?string  $authorizedAt
     * @phpstan-pure
     */
    public function __construct(string $id, Category $category, string $amount, CardTransactionCurrency $currency, string $description, string $postedAt, ?string $cardAccountId = null, ?string $customerId = null, ?string $billingAmount = null, ?string $merchantCategoryCode = null, ?string $merchantName = null, ?string $merchantLocation = null, ?CardLocalTransactionDetails $localTransactionDetails = null, ?string $authorizedAt = null)
    {
        $this->id = $id;
        $this->category = $category;
        $this->amount = $amount;
        $this->currency = $currency;
        $this->description = $description;
        $this->postedAt = $postedAt;
        $this->cardAccountId = $cardAccountId;
        $this->customerId = $customerId;
        $this->billingAmount = $billingAmount;
        $this->merchantCategoryCode = $merchantCategoryCode;
        $this->merchantName = $merchantName;
        $this->merchantLocation = $merchantLocation;
        $this->localTransactionDetails = $localTransactionDetails;
        $this->authorizedAt = $authorizedAt;
    }
}