<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


/** Status of the card account */
enum CardAccountStatus: string
{
    case Active = 'active';
    case Pending = 'pending';
    case Inactive = 'inactive';
    case Frozen = 'frozen';
}
