<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


/** The mobile wallet provider */
enum CardWalletProvider: string
{
    case ApplePay = 'apple_pay';
    case GooglePay = 'google_pay';
}
