<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


/** CardAuthorizationVerificationData - Information on verifications that were performed on information that the cardholder provided to the merchant. */
class CardAuthorizationVerificationData
{
    /**
     * Whether the cardholder provided an address and if it matched the cardholder’s address on file.
     *
     * @var ?AddressCheck $addressCheck
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('address_check')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\AddressCheck|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AddressCheck $addressCheck = null;

    /**
     * Whether the cardholder provided a postal code and if it matched the cardholder’s postal code on file.
     *
     * @var ?AddressPostalCodeCheck $addressPostalCodeCheck
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('address_postal_code_check')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\AddressPostalCodeCheck|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AddressPostalCodeCheck $addressPostalCodeCheck = null;

    /**
     * Whether the cardholder provided a CVV and if it matched the CVV on record.
     *
     * @var ?CvvCheck $cvvCheck
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cvv_check')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\CvvCheck|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CvvCheck $cvvCheck = null;

    /**
     * Whether the cardholder provided a PIN and if it matched the PIN on record.
     *
     * @var ?PinCheck $pinCheck
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pin_check')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\PinCheck|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PinCheck $pinCheck = null;

    /**
     * The results of the 3DS authentication attempt for this authorization, if applicable.
     *
     * @var ?ThreeDSecureCheck $threeDSecureCheck
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('three_d_secure_check')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\ThreeDSecureCheck|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ThreeDSecureCheck $threeDSecureCheck = null;

    /**
     * @param  ?AddressCheck  $addressCheck
     * @param  ?AddressPostalCodeCheck  $addressPostalCodeCheck
     * @param  ?CvvCheck  $cvvCheck
     * @param  ?PinCheck  $pinCheck
     * @param  ?ThreeDSecureCheck  $threeDSecureCheck
     * @phpstan-pure
     */
    public function __construct(?AddressCheck $addressCheck = null, ?AddressPostalCodeCheck $addressPostalCodeCheck = null, ?CvvCheck $cvvCheck = null, ?PinCheck $pinCheck = null, ?ThreeDSecureCheck $threeDSecureCheck = null)
    {
        $this->addressCheck = $addressCheck;
        $this->addressPostalCodeCheck = $addressPostalCodeCheck;
        $this->cvvCheck = $cvvCheck;
        $this->pinCheck = $pinCheck;
        $this->threeDSecureCheck = $threeDSecureCheck;
    }
}