<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


/** CardWithdrawal - A card funds withdrawal */
class CardWithdrawal
{
    /**
     * A UUID that uniquely identifies a resource
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * The amount represented as a decimal string
     *
     * @var string $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    public string $amount;

    /**
     *
     * @var CardsCryptoCurrency $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\CardsCryptoCurrency')]
    public CardsCryptoCurrency $currency;

    /**
     *
     * @var CardWithdrawalDestination $destination
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('destination')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\CardWithdrawalDestination')]
    public CardWithdrawalDestination $destination;

    /**
     * Timestamp when the withdrawal was created, in ISO8601 format
     *
     * @var string $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    public string $createdAt;

    /**
     * Timestamp when the withdrawal was last updated, in ISO8601 format
     *
     * @var string $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updated_at')]
    public string $updatedAt;

    /**
     * The type of the withdrawal. Defaults to `top_up_balance_withdrawal`.
     *
     * @var ?CardWithdrawalType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\CardWithdrawalType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CardWithdrawalType $type = null;

    /**
     * An optional client-provided note for the withdrawal
     *
     * @var ?string $clientNote
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('client_note')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $clientNote = null;

    /**
     * @param  string  $id
     * @param  string  $amount
     * @param  CardsCryptoCurrency  $currency
     * @param  CardWithdrawalDestination  $destination
     * @param  string  $createdAt
     * @param  string  $updatedAt
     * @param  ?CardWithdrawalType  $type
     * @param  ?string  $clientNote
     * @phpstan-pure
     */
    public function __construct(string $id, string $amount, CardsCryptoCurrency $currency, CardWithdrawalDestination $destination, string $createdAt, string $updatedAt, ?CardWithdrawalType $type = null, ?string $clientNote = null)
    {
        $this->id = $id;
        $this->amount = $amount;
        $this->currency = $currency;
        $this->destination = $destination;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->type = $type;
        $this->clientNote = $clientNote;
    }
}