<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


/** The type of the withdrawal. Defaults to `top_up_balance_withdrawal`. */
enum CardWithdrawalType: string
{
    case TopUpBalanceWithdrawal = 'top_up_balance_withdrawal';
    case Fee = 'fee';
}
