<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


/** CardUnfreezeResponse - Card unfreeze response */
class CardUnfreezeResponse
{
    /**
     * A UUID that uniquely identifies a resource
     *
     * @var string $cardAccountId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('card_account_id')]
    public string $cardAccountId;

    /**
     * The initiator of the removed freeze
     *
     * @var mixed $initiator
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('initiator')]
    #[\Speakeasy\Serializer\Annotation\Type('mixed')]
    public mixed $initiator;

    /**
     * The reason of the removed freeze
     *
     * @var mixed $reason
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('reason')]
    #[\Speakeasy\Serializer\Annotation\Type('mixed')]
    public mixed $reason;

    /**
     * The creation time of the removed freeze, in ISO8601 format
     *
     * @var mixed $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    #[\Speakeasy\Serializer\Annotation\Type('mixed')]
    public mixed $createdAt;

    /**
     * The processing status of the unfreeze request
     *
     * @var CardUnfreezeResponseStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\CardUnfreezeResponseStatus')]
    public CardUnfreezeResponseStatus $status;

    /**
     * The reason detail of the removed freeze
     *
     * @var mixed $reasonDetail
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('reason_detail')]
    #[\Speakeasy\Serializer\Annotation\Type('mixed')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public mixed $reasonDetail = null;

    /**
     * The start time of the removed freeze, in ISO8601 format
     *
     * @var mixed $startingAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('starting_at')]
    #[\Speakeasy\Serializer\Annotation\Type('mixed')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public mixed $startingAt = null;

    /**
     * The end time of the removed freeze, in ISO8601 format
     *
     * @var mixed $endingAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ending_at')]
    #[\Speakeasy\Serializer\Annotation\Type('mixed')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public mixed $endingAt = null;

    /**
     * @param  string  $cardAccountId
     * @param  mixed  $initiator
     * @param  mixed  $reason
     * @param  mixed  $createdAt
     * @param  CardUnfreezeResponseStatus  $status
     * @param  mixed  $reasonDetail
     * @param  mixed  $startingAt
     * @param  mixed  $endingAt
     * @phpstan-pure
     */
    public function __construct(string $cardAccountId, mixed $initiator, mixed $reason, mixed $createdAt, CardUnfreezeResponseStatus $status, mixed $reasonDetail = null, mixed $startingAt = null, mixed $endingAt = null)
    {
        $this->cardAccountId = $cardAccountId;
        $this->initiator = $initiator;
        $this->reason = $reason;
        $this->createdAt = $createdAt;
        $this->status = $status;
        $this->reasonDetail = $reasonDetail;
        $this->startingAt = $startingAt;
        $this->endingAt = $endingAt;
    }
}