<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


/** The type of card that the design applies to */
enum CardDesignsType: string
{
    case Virtual = 'virtual';
    case Physical = 'physical';
}
