<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


class CardAccount
{
    /**
     * A UUID that uniquely identifies a resource
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * A UUID that uniquely identifies a resource
     *
     * @var string $customerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customer_id')]
    public string $customerId;

    /**
     * Status of the card account
     *
     * @var CardAccountStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\CardAccountStatus')]
    public CardAccountStatus $status;

    /**
     * Balances of the card account
     *
     * @var CardBalances $balances
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('balances')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\CardBalances')]
    public CardBalances $balances;

    /**
     * $freezes
     *
     * @var array<Freeze> $freezes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('freezes')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\ReThink\BridgeSDK\Models\Components\Freeze>')]
    public array $freezes;

    /**
     * The client-provided reference ID
     *
     * @var ?string $clientReferenceId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('client_reference_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $clientReferenceId = null;

    /**
     * The name of the cardholder associated to the card. By default, this will be the name of the associated customer. To override the cardholder name, you can contact Bridge support.
     *
     * @var ?CardholderName $cardholderName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cardholder_name')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\CardholderName|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CardholderName $cardholderName = null;

    /**
     * An expiring URL used to render the card image, with a validity period of 5 minutes. _Note:_ This field will be deprecated in favor of the more secure and scalable card details API. Please see the integration guide on [safely revealing card details](https://apidocs.bridge.xyz/docs/safely-reveal-card-details-to-customers) for more information.
     *
     * @var ?string $cardImageUrl
     * @deprecated  field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('card_image_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $cardImageUrl = null;

    /**
     * An optional detailed explanation for the card account status
     *
     * @var ?string $statusReason
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status_reason')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $statusReason = null;

    /**
     * Details of the issued card. This object contains enough payment card details to identify the issued card, but only provides the last four digits of the card number to maintain security.
     *
     * @var ?CardDetails $cardDetails
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('card_details')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\CardDetails|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CardDetails $cardDetails = null;

    /**
     * The crypto account for a self-custodial card account. This field is not supported for a Bridge-custodial card funding setup (note that if you are on cards trial, you are automatically on a custodial funding setup).
     *
     * @var ?CardCryptoAccount $cryptoAccount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('crypto_account')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\CardCryptoAccount|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CardCryptoAccount $cryptoAccount = null;

    /**
     * Funding instructions applicable only to the top-up card funding strategy, which is configured at the developer level
     *
     * @var ?CardAccountFundingInstructions $fundingInstructions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('funding_instructions')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\CardAccountFundingInstructions|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CardAccountFundingInstructions $fundingInstructions = null;

    /**
     * $additionalFundingInstructions
     *
     * @var ?array<CardAccountFundingInstructions> $additionalFundingInstructions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('additional_funding_instructions')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\ReThink\BridgeSDK\Models\Components\CardAccountFundingInstructions>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $additionalFundingInstructions = null;

    /**
     * @param  string  $id
     * @param  string  $customerId
     * @param  CardAccountStatus  $status
     * @param  CardBalances  $balances
     * @param  array<Freeze>  $freezes
     * @param  ?string  $clientReferenceId
     * @param  ?CardholderName  $cardholderName
     * @param  ?string  $cardImageUrl
     * @param  ?string  $statusReason
     * @param  ?CardDetails  $cardDetails
     * @param  ?CardCryptoAccount  $cryptoAccount
     * @param  ?CardAccountFundingInstructions  $fundingInstructions
     * @param  ?array<CardAccountFundingInstructions>  $additionalFundingInstructions
     * @phpstan-pure
     */
    public function __construct(string $id, string $customerId, CardAccountStatus $status, CardBalances $balances, array $freezes, ?string $clientReferenceId = null, ?CardholderName $cardholderName = null, ?string $cardImageUrl = null, ?string $statusReason = null, ?CardDetails $cardDetails = null, ?CardCryptoAccount $cryptoAccount = null, ?CardAccountFundingInstructions $fundingInstructions = null, ?array $additionalFundingInstructions = null)
    {
        $this->id = $id;
        $this->customerId = $customerId;
        $this->status = $status;
        $this->balances = $balances;
        $this->freezes = $freezes;
        $this->clientReferenceId = $clientReferenceId;
        $this->cardholderName = $cardholderName;
        $this->cardImageUrl = $cardImageUrl;
        $this->statusReason = $statusReason;
        $this->cardDetails = $cardDetails;
        $this->cryptoAccount = $cryptoAccount;
        $this->fundingInstructions = $fundingInstructions;
        $this->additionalFundingInstructions = $additionalFundingInstructions;
    }
}