<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


enum CardTransactionStatusParameter: string
{
    case Pending = 'pending';
    case Posted = 'posted';
}
