<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


/** CardAuthorization - A pending card authorization */
class CardAuthorization
{
    /**
     * A UUID that uniquely identifies a resource
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * The amount represented as a decimal string
     *
     * @var string $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    public string $amount;

    /**
     *
     * @var FiatCurrency $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\FiatCurrency')]
    public FiatCurrency $currency;

    /**
     * A merchant category code for card transactions (e.g., '5712')
     *
     * @var string $merchantCategoryCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('merchant_category_code')]
    public string $merchantCategoryCode;

    /**
     * A description of the card transaction, including the merchant's name and location information
     *
     * @var string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public string $description;

    /**
     * Timestamp when the card transaction was authorized, in ISO8601 format
     *
     * @var string $authorizedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('authorized_at')]
    public string $authorizedAt;

    /**
     *
     * @var Details $details
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('details')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\Details')]
    public Details $details;

    /**
     * The billing amount, represented as a decimal string. The billing amount is the amount of the transaction excluding any additional hold. This amount should be present on all purchases, but will only differ from the amount field for some merchant categories in which an upcharge is involved (e.g. gas stations, hotels).
     *
     * @var ?string $billingAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billing_amount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $billingAmount = null;

    /**
     * Details of a transaction processed in a local currency other than USD, with currency conversion applied
     *
     * @var ?CardLocalTransactionDetails $localTransactionDetails
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('local_transaction_details')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\CardLocalTransactionDetails|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CardLocalTransactionDetails $localTransactionDetails = null;

    /**
     * Information on verifications that were performed on information that the cardholder provided to the merchant.
     *
     * @var ?CardAuthorizationVerificationData $verificationData
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('verification_data')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\CardAuthorizationVerificationData|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CardAuthorizationVerificationData $verificationData = null;

    /**
     * @param  string  $id
     * @param  string  $amount
     * @param  FiatCurrency  $currency
     * @param  string  $merchantCategoryCode
     * @param  string  $description
     * @param  string  $authorizedAt
     * @param  Details  $details
     * @param  ?string  $billingAmount
     * @param  ?CardLocalTransactionDetails  $localTransactionDetails
     * @param  ?CardAuthorizationVerificationData  $verificationData
     * @phpstan-pure
     */
    public function __construct(string $id, string $amount, FiatCurrency $currency, string $merchantCategoryCode, string $description, string $authorizedAt, Details $details, ?string $billingAmount = null, ?CardLocalTransactionDetails $localTransactionDetails = null, ?CardAuthorizationVerificationData $verificationData = null)
    {
        $this->id = $id;
        $this->amount = $amount;
        $this->currency = $currency;
        $this->merchantCategoryCode = $merchantCategoryCode;
        $this->description = $description;
        $this->authorizedAt = $authorizedAt;
        $this->details = $details;
        $this->billingAmount = $billingAmount;
        $this->localTransactionDetails = $localTransactionDetails;
        $this->verificationData = $verificationData;
    }
}