<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


/** The processing status of the unfreeze request */
enum CardUnfreezeResponseStatus: string
{
    case FreezeRemoved = 'freeze_removed';
}
