<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


enum CardTransactionCategoryFamilyParameter: string
{
    case Cards = 'cards';
    case Crypto = 'crypto';
}
