<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


/** CardAccountFundingInstructions - Funding instructions applicable only to the top-up card funding strategy, which is configured at the developer level */
class CardAccountFundingInstructions
{
    /**
     *
     * @var CardsCryptoCurrency $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\CardsCryptoCurrency')]
    public CardsCryptoCurrency $currency;

    /**
     *
     * @var OfframpChainForCards $chain
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('chain')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\OfframpChainForCards')]
    public OfframpChainForCards $chain;

    /**
     * The deposit address provided by Bridge to fund the card account
     *
     * @var string $address
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('address')]
    public string $address;

    /**
     * If present, this is the message that the customer MUST include in their on-chain funding transfers. It is only applicable to memo-based blockchains such as Stellar and Tron
     *
     * @var ?string $memo
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('memo')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $memo = null;

    /**
     * @param  CardsCryptoCurrency  $currency
     * @param  OfframpChainForCards  $chain
     * @param  string  $address
     * @param  ?string  $memo
     * @phpstan-pure
     */
    public function __construct(CardsCryptoCurrency $currency, OfframpChainForCards $chain, string $address, ?string $memo = null)
    {
        $this->currency = $currency;
        $this->chain = $chain;
        $this->address = $address;
        $this->memo = $memo;
    }
}