<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


/** The category of the transaction */
enum Category: string
{
    case Adjustment = 'adjustment';
    case Fee = 'fee';
    case Purchase = 'purchase';
    case Refund = 'refund';
    case CryptoFunding = 'crypto_funding';
    case CryptoReturn = 'crypto_return';
    case CryptoWithdrawal = 'crypto_withdrawal';
}
