<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


class Country
{
    /**
     * The name of the country
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * The three-letter alpha-3 country code as defined in the ISO 3166-1 spec, used in Bridge APIs
     *
     * @var string $alpha3
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('alpha3')]
    public string $alpha3;

    /**
     * A list of subdivisions for the country
     *
     * @var array<Subdivision> $subdivisions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subdivisions')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\ReThink\BridgeSDK\Models\Components\Subdivision>')]
    public array $subdivisions;

    /**
     * A [Ruby-formatted regular expression](https://ruby-doc.org/3.4.2/Regexp.html) that matches valid postal codes for the country, or null if the country does not use postal codes.
     *
     * @var ?string $postalCodeFormat
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('postal_code_format')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $postalCodeFormat = null;

    /**
     * @param  string  $name
     * @param  string  $alpha3
     * @param  array<Subdivision>  $subdivisions
     * @param  ?string  $postalCodeFormat
     * @phpstan-pure
     */
    public function __construct(string $name, string $alpha3, array $subdivisions, ?string $postalCodeFormat = null)
    {
        $this->name = $name;
        $this->alpha3 = $alpha3;
        $this->subdivisions = $subdivisions;
        $this->postalCodeFormat = $postalCodeFormat;
    }
}