<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


class CreateBusinessCustomerPayload
{
    /**
     * Type of the customer (individual vs. business)
     *
     * @var CreateBusinessCustomerPayloadType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\CreateBusinessCustomerPayloadType')]
    public CreateBusinessCustomerPayloadType $type;

    /**
     * The official registered name of the business as documented with government authorities.
     *
     * @var string $businessLegalName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('business_legal_name')]
    public string $businessLegalName;

    /**
     * The trading name or DBA (Doing Business As) name under which the business operates publicly.
     *
     * @var string $businessTradeName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('business_trade_name')]
    public string $businessTradeName;

    /**
     * A brief summary of the business
     *
     * @var string $businessDescription
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('business_description')]
    public string $businessDescription;

    /**
     * The business's primary email address
     *
     * @var string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    public string $email;

    /**
     * How the business is legally registered
     *
     * @var CreateBusinessCustomerPayloadBusinessType $businessType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('business_type')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\CreateBusinessCustomerPayloadBusinessType')]
    public CreateBusinessCustomerPayloadBusinessType $businessType;

    /**
     *
     * @var Address2025WinterRefresh $registeredAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('registered_address')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\Address2025WinterRefresh')]
    public Address2025WinterRefresh $registeredAddress;

    /**
     *
     * @var Address2025WinterRefresh $physicalAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('physical_address')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\Address2025WinterRefresh')]
    public Address2025WinterRefresh $physicalAddress;

    /**
     * The ID of the signed agreement that the customer completed. You can get a signed agreement id for a _new_ customer by following [this guide](https://apidocs.bridge.xyz/docs/terms-of-service#tos-acceptance-for-a-new-customer).
     *
     *
     *
     * @var string $signedAgreementId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('signed_agreement_id')]
    public string $signedAgreementId;

    /**
     * Whether the business is a DAO (Decentralized Autonomous Organization)
     *
     * @var bool $isDao
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('is_dao')]
    public bool $isDao;

    /**
     * List of notable people associated with the business such as UBOs.
     *
     * @var array<AssociatedPerson> $associatedPersons
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('associated_persons')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\ReThink\BridgeSDK\Models\Components\AssociatedPerson>')]
    public array $associatedPersons;

    /**
     * The industry in which this business operates. Click [here](https://apidocs.bridge.xyz/page/business-industry-list-updated-2022-naics-codes) for the complete list of valid industries and codes.
     *
     * @var array<string> $businessIndustry
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('business_industry')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>')]
    public array $businessIndustry;

    /**
     * The business has at least one intermediate legal entity owner with 25% or more ownership
     *
     * @var bool $hasMaterialIntermediaryOwnership
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('has_material_intermediary_ownership')]
    public bool $hasMaterialIntermediaryOwnership;

    /**
     * What is the primary purpose of the business account?
     *
     * @var CreateBusinessCustomerPayloadAccountPurpose $accountPurpose
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('account_purpose')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\CreateBusinessCustomerPayloadAccountPurpose')]
    public CreateBusinessCustomerPayloadAccountPurpose $accountPurpose;

    /**
     * The source of funds for the business, e.g. profits, income, venture capital, etc.
     *
     * @var CreateBusinessCustomerPayloadSourceOfFunds $sourceOfFunds
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_of_funds')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\CreateBusinessCustomerPayloadSourceOfFunds')]
    public CreateBusinessCustomerPayloadSourceOfFunds $sourceOfFunds;

    /**
     * $identifyingInformation
     *
     * @var array<IdentifyingInformation> $identifyingInformation
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('identifying_information')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\ReThink\BridgeSDK\Models\Components\IdentifyingInformation>')]
    public array $identifyingInformation;

    /**
     * Please click "ADD OBJECT" for more information.
     *
     * @var array<BusinessDocuments> $documents
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('documents')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\ReThink\BridgeSDK\Models\Components\BusinessDocuments>')]
    public array $documents;

    /**
     * Required if `business_legal_name` includes any non Latin-1 characters. Acceptable characters - Latin-1 Unicode Character Range: À-ÖØ-ßà-öø-ÿ; Standard Unicode Character Range:  -~
     *
     * @var ?string $transliteratedBusinessLegalName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transliterated_business_legal_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $transliteratedBusinessLegalName = null;

    /**
     * Required if `business_trade` includes any non Latin-1 characters. Acceptable characters - Latin-1 Unicode Character Range: À-ÖØ-ßà-öø-ÿ; Standard Unicode Character Range:  -~
     *
     * @var ?string $transliteratedBusinessTradeName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transliterated_business_trade_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $transliteratedBusinessTradeName = null;

    /**
     * The business's primary website/web presence. A document with purpose 'proof_of_nature_of_business' is required if this is not provided
     *
     * @var ?string $primaryWebsite
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('primary_website')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $primaryWebsite = null;

    /**
     * The business's other websites and social media handles
     *
     * @var ?array<string> $otherWebsites
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('other_websites')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $otherWebsites = null;

    /**
     *
     * @var ?Address2025WinterRefresh $transliteratedRegisteredAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transliterated_registered_address')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\Address2025WinterRefresh|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Address2025WinterRefresh $transliteratedRegisteredAddress = null;

    /**
     *
     * @var ?Address2025WinterRefresh $transliteratedPhysicalAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transliterated_physical_address')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\Address2025WinterRefresh|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Address2025WinterRefresh $transliteratedPhysicalAddress = null;

    /**
     * Required if `conducts_money_services` is true. A detailed description of the business's compliance and anti-money laundering controls and practices.
     *
     * @var ?string $complianceScreeningExplanation
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('compliance_screening_explanation')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $complianceScreeningExplanation = null;

    /**
     * List of endorsements to request for this customer. If omitted, we'll attempt to grant `base` and `sepa`.
     *
     *
     *
     * @var ?array<EndorsementType> $endorsements
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('endorsements')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\ReThink\BridgeSDK\Models\Components\EndorsementType>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $endorsements = null;

    /**
     * A list of public exchanges that the company is traded on if applicable.
     *
     * @var ?array<CreateBusinessCustomerPayloadPubliclyTradedListing> $publiclyTradedListings
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('publicly_traded_listings')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\ReThink\BridgeSDK\Models\Components\CreateBusinessCustomerPayloadPubliclyTradedListing>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $publiclyTradedListings = null;

    /**
     * The applicable beneficial ownership threshold for the submitted `associated_persons` information. Valid values are between 5 to 25. Default value is 25.
     *
     * @var ?int $ownershipThreshold
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ownership_threshold')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $ownershipThreshold = null;

    /**
     * Estimated annual revenue in USD
     *
     *
     * _Required for high risk customers. More information found [here](https://apidocs.bridge.xyz/docs/business-accounts)_
     *
     *
     * @var ?CreateBusinessCustomerPayloadEstimatedAnnualRevenueUsd $estimatedAnnualRevenueUsd
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('estimated_annual_revenue_usd')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\CreateBusinessCustomerPayloadEstimatedAnnualRevenueUsd|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CreateBusinessCustomerPayloadEstimatedAnnualRevenueUsd $estimatedAnnualRevenueUsd = null;

    /**
     * Expected monthly payments in USD
     *
     *
     * _Required for high risk customers. More information found [here](https://apidocs.bridge.xyz/docs/business-accounts)_
     *
     *
     * @var ?int $expectedMonthlyPaymentsUsd
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expected_monthly_payments_usd')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $expectedMonthlyPaymentsUsd = null;

    /**
     * Does the business operate in any prohibited countries?
     *
     *
     * _Required for high risk customers. More information found [here](https://apidocs.bridge.xyz/docs/business-accounts)_
     *
     *
     * @var ?bool $operatesInProhibitedCountries
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('operates_in_prohibited_countries')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $operatesInProhibitedCountries = null;

    /**
     * Required if the primary purpose is 'other'.
     *
     * @var ?string $accountPurposeOther
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('account_purpose_other')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $accountPurposeOther = null;

    /**
     * An explanation of the high risk activities that the business performs. 
     *
     *
     * _Required if `high_risk_activities` contains entries other than `none_of_the_above`_
     *
     *
     * @var ?string $highRiskActivitiesExplanation
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('high_risk_activities_explanation')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $highRiskActivitiesExplanation = null;

    /**
     * List of high-risk activities the business is involved in.
     *
     *
     * _Required for high risk customers. More information found [here](https://apidocs.bridge.xyz/docs/business-accounts)_
     *
     *
     * @var ?array<CreateBusinessCustomerPayloadHighRiskActivity> $highRiskActivities
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('high_risk_activities')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\ReThink\BridgeSDK\Models\Components\CreateBusinessCustomerPayloadHighRiskActivity>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $highRiskActivities = null;

    /**
     * Description of the source of funds for the business' account.
     *
     *
     * _Required for high risk customers. More information found [here](https://apidocs.bridge.xyz/docs/business-accounts)_
     *
     *
     * @var ?string $sourceOfFundsDescription
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_of_funds_description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $sourceOfFundsDescription = null;

    /**
     * The business offers money services, investment products, and/or other financial services.
     *
     *
     * _Required for high risk customers. More information found [here](https://apidocs.bridge.xyz/docs/business-accounts)_
     *
     *
     * @var ?bool $conductsMoneyServices
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('conducts_money_services')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $conductsMoneyServices = null;

    /**
     * The business plans to conduct money services, investment products, and/or other financial services using its Bridge account. A document with purpose 'flow_of_funds' is required if this is true.
     *
     *
     * _Required if `conducts_money_services` is true_
     *
     *
     * @var ?bool $conductsMoneyServicesUsingBridge
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('conducts_money_services_using_bridge')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $conductsMoneyServicesUsingBridge = null;

    /**
     * Description of the money services offered by the business.
     *
     *
     * _Required if `conducts_money_services` is true_
     *
     *
     * @var ?string $conductsMoneyServicesDescription
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('conducts_money_services_description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $conductsMoneyServicesDescription = null;

    /**
     *
     * @var ?CreateBusinessCustomerPayloadRegulatedActivity $regulatedActivity
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('regulated_activity')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\CreateBusinessCustomerPayloadRegulatedActivity|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CreateBusinessCustomerPayloadRegulatedActivity $regulatedActivity = null;

    /**
     * @param  CreateBusinessCustomerPayloadType  $type
     * @param  string  $businessLegalName
     * @param  string  $businessTradeName
     * @param  string  $businessDescription
     * @param  string  $email
     * @param  CreateBusinessCustomerPayloadBusinessType  $businessType
     * @param  Address2025WinterRefresh  $registeredAddress
     * @param  Address2025WinterRefresh  $physicalAddress
     * @param  string  $signedAgreementId
     * @param  bool  $isDao
     * @param  array<AssociatedPerson>  $associatedPersons
     * @param  array<string>  $businessIndustry
     * @param  bool  $hasMaterialIntermediaryOwnership
     * @param  CreateBusinessCustomerPayloadAccountPurpose  $accountPurpose
     * @param  CreateBusinessCustomerPayloadSourceOfFunds  $sourceOfFunds
     * @param  array<IdentifyingInformation>  $identifyingInformation
     * @param  array<BusinessDocuments>  $documents
     * @param  ?string  $transliteratedBusinessLegalName
     * @param  ?string  $transliteratedBusinessTradeName
     * @param  ?string  $primaryWebsite
     * @param  ?array<string>  $otherWebsites
     * @param  ?Address2025WinterRefresh  $transliteratedRegisteredAddress
     * @param  ?Address2025WinterRefresh  $transliteratedPhysicalAddress
     * @param  ?string  $complianceScreeningExplanation
     * @param  ?array<EndorsementType>  $endorsements
     * @param  ?array<CreateBusinessCustomerPayloadPubliclyTradedListing>  $publiclyTradedListings
     * @param  ?int  $ownershipThreshold
     * @param  ?CreateBusinessCustomerPayloadEstimatedAnnualRevenueUsd  $estimatedAnnualRevenueUsd
     * @param  ?int  $expectedMonthlyPaymentsUsd
     * @param  ?bool  $operatesInProhibitedCountries
     * @param  ?string  $accountPurposeOther
     * @param  ?string  $highRiskActivitiesExplanation
     * @param  ?array<CreateBusinessCustomerPayloadHighRiskActivity>  $highRiskActivities
     * @param  ?string  $sourceOfFundsDescription
     * @param  ?bool  $conductsMoneyServices
     * @param  ?bool  $conductsMoneyServicesUsingBridge
     * @param  ?string  $conductsMoneyServicesDescription
     * @param  ?CreateBusinessCustomerPayloadRegulatedActivity  $regulatedActivity
     * @phpstan-pure
     */
    public function __construct(CreateBusinessCustomerPayloadType $type, string $businessLegalName, string $businessTradeName, string $businessDescription, string $email, CreateBusinessCustomerPayloadBusinessType $businessType, Address2025WinterRefresh $registeredAddress, Address2025WinterRefresh $physicalAddress, string $signedAgreementId, bool $isDao, array $associatedPersons, array $businessIndustry, bool $hasMaterialIntermediaryOwnership, CreateBusinessCustomerPayloadAccountPurpose $accountPurpose, CreateBusinessCustomerPayloadSourceOfFunds $sourceOfFunds, array $identifyingInformation, array $documents, ?string $transliteratedBusinessLegalName = null, ?string $transliteratedBusinessTradeName = null, ?string $primaryWebsite = null, ?array $otherWebsites = null, ?Address2025WinterRefresh $transliteratedRegisteredAddress = null, ?Address2025WinterRefresh $transliteratedPhysicalAddress = null, ?string $complianceScreeningExplanation = null, ?array $endorsements = null, ?array $publiclyTradedListings = null, ?int $ownershipThreshold = null, ?CreateBusinessCustomerPayloadEstimatedAnnualRevenueUsd $estimatedAnnualRevenueUsd = null, ?int $expectedMonthlyPaymentsUsd = null, ?bool $operatesInProhibitedCountries = null, ?string $accountPurposeOther = null, ?string $highRiskActivitiesExplanation = null, ?array $highRiskActivities = null, ?string $sourceOfFundsDescription = null, ?bool $conductsMoneyServices = null, ?bool $conductsMoneyServicesUsingBridge = null, ?string $conductsMoneyServicesDescription = null, ?CreateBusinessCustomerPayloadRegulatedActivity $regulatedActivity = null)
    {
        $this->type = $type;
        $this->businessLegalName = $businessLegalName;
        $this->businessTradeName = $businessTradeName;
        $this->businessDescription = $businessDescription;
        $this->email = $email;
        $this->businessType = $businessType;
        $this->registeredAddress = $registeredAddress;
        $this->physicalAddress = $physicalAddress;
        $this->signedAgreementId = $signedAgreementId;
        $this->isDao = $isDao;
        $this->associatedPersons = $associatedPersons;
        $this->businessIndustry = $businessIndustry;
        $this->hasMaterialIntermediaryOwnership = $hasMaterialIntermediaryOwnership;
        $this->accountPurpose = $accountPurpose;
        $this->sourceOfFunds = $sourceOfFunds;
        $this->identifyingInformation = $identifyingInformation;
        $this->documents = $documents;
        $this->transliteratedBusinessLegalName = $transliteratedBusinessLegalName;
        $this->transliteratedBusinessTradeName = $transliteratedBusinessTradeName;
        $this->primaryWebsite = $primaryWebsite;
        $this->otherWebsites = $otherWebsites;
        $this->transliteratedRegisteredAddress = $transliteratedRegisteredAddress;
        $this->transliteratedPhysicalAddress = $transliteratedPhysicalAddress;
        $this->complianceScreeningExplanation = $complianceScreeningExplanation;
        $this->endorsements = $endorsements;
        $this->publiclyTradedListings = $publiclyTradedListings;
        $this->ownershipThreshold = $ownershipThreshold;
        $this->estimatedAnnualRevenueUsd = $estimatedAnnualRevenueUsd;
        $this->expectedMonthlyPaymentsUsd = $expectedMonthlyPaymentsUsd;
        $this->operatesInProhibitedCountries = $operatesInProhibitedCountries;
        $this->accountPurposeOther = $accountPurposeOther;
        $this->highRiskActivitiesExplanation = $highRiskActivitiesExplanation;
        $this->highRiskActivities = $highRiskActivities;
        $this->sourceOfFundsDescription = $sourceOfFundsDescription;
        $this->conductsMoneyServices = $conductsMoneyServices;
        $this->conductsMoneyServicesUsingBridge = $conductsMoneyServicesUsingBridge;
        $this->conductsMoneyServicesDescription = $conductsMoneyServicesDescription;
        $this->regulatedActivity = $regulatedActivity;
    }
}