<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


/**
 * Estimated annual revenue in USD
 *
 *
 * _Required for high risk customers. More information found [here](https://apidocs.bridge.xyz/docs/business-accounts)_
 *
 */
enum CreateBusinessCustomerPayloadEstimatedAnnualRevenueUsd: string
{
    case Zero99999 = '0_99999';
    case OneHundredThousand999999 = '100000_999999';
    case OneMillion9999999 = '1000000_9999999';
    case TenMillion49999999 = '10000000_49999999';
    case FiftyMillion249999999 = '50000000_249999999';
    case TwoHundredAndFiftyMillionPlus = '250000000_plus';
}
