<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


class CreateLiquidationAddressResponse
{
    /**
     *
     * @var LiquidationAddressSourceCurrency $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\LiquidationAddressSourceCurrency')]
    public LiquidationAddressSourceCurrency $currency;

    /**
     *
     * @var LiquidationAddressSourceChain $chain
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('chain')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\LiquidationAddressSourceChain')]
    public LiquidationAddressSourceChain $chain;

    /**
     * The payment rail that Bridge will use to send funds to the customer.
     *
     * @var mixed $destinationPaymentRail
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('destination_payment_rail')]
    #[\Speakeasy\Serializer\Annotation\Type('mixed')]
    public mixed $destinationPaymentRail;

    /**
     * The currency that Bridge will use to send funds to the customer.
     *
     * @var mixed $destinationCurrency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('destination_currency')]
    #[\Speakeasy\Serializer\Annotation\Type('mixed')]
    public mixed $destinationCurrency;

    /**
     * External bank account to which Bridge will send the funds.
     *
     * @var mixed $externalAccountId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('external_account_id')]
    #[\Speakeasy\Serializer\Annotation\Type('mixed')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public mixed $externalAccountId = null;

    /**
     * The developer's prefunded account to which Bridge will send the funds.
     *
     * @var mixed $prefundedAccountId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('prefunded_account_id')]
    #[\Speakeasy\Serializer\Annotation\Type('mixed')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public mixed $prefundedAccountId = null;

    /**
     * A UUID that uniquely identifies a resource
     *
     * @var ?string $bridgeWalletId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bridge_wallet_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $bridgeWalletId = null;

    /**
     * A message to be sent with a wire transfer.
     *
     * @var mixed $destinationWireMessage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('destination_wire_message')]
    #[\Speakeasy\Serializer\Annotation\Type('mixed')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public mixed $destinationWireMessage = null;

    /**
     * A reference message to be sent with a SEPA transaction.
     *
     * @var mixed $destinationSepaReference
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('destination_sepa_reference')]
    #[\Speakeasy\Serializer\Annotation\Type('mixed')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public mixed $destinationSepaReference = null;

    /**
     * A reference message to be sent with an ACH transaction. It can be at most 10 characters, A-Z, a-z, 0-9, and spaces.
     *
     * @var ?string $destinationAchReference
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('destination_ach_reference')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $destinationAchReference = null;

    /**
     * A payment reference message or remittance information to be included in a SPEI transaction. The allowed characters are alphanumeric `a-z`, `A-Z`, `0-9`, and space
     *
     * @var ?string $destinationSpeiReference
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('destination_spei_reference')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $destinationSpeiReference = null;

    /**
     * A payment reference message for newer payment rails (e.g. Pix).
     *
     * @var ?string $destinationReference
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('destination_reference')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $destinationReference = null;

    /**
     * The crypto wallet address that Bridge will use to send funds to the customer.
     *
     * @var ?string $destinationAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('destination_address')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $destinationAddress = null;

    /**
     * The memo to include in the transaction, for blockchains that support memos only
     *
     * @var ?string $destinationBlockchainMemo
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('destination_blockchain_memo')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $destinationBlockchainMemo = null;

    /**
     * The crypto wallet address that Bridge will use to return funds to the customer in case of a failed transaction. This address must be on the same chain specified for the liquidation address. Please note, this functionality is not supported on Stellar.
     *
     * @var ?string $returnAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('return_address')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $returnAddress = null;

    /**
     * The blockchain address the customer will send funds to.
     *
     * @var ?string $address
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('address')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $address = null;

    /**
     * The state of the liquidation address. It could be "active" or "deactivated"
     *
     * @var ?string $state
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('state')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $state = null;

    /**
     * The developer fee percent that will be applied to this Liquidation Address or null to use the default fee. The value is a base 100 percentage, i.e. 10.2% is 10.2 in the API.
     *
     * @var ?string $customDeveloperFeePercent
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('custom_developer_fee_percent')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $customDeveloperFeePercent = null;

    /**
     * @param  LiquidationAddressSourceCurrency  $currency
     * @param  LiquidationAddressSourceChain  $chain
     * @param  mixed  $destinationPaymentRail
     * @param  mixed  $destinationCurrency
     * @param  mixed  $externalAccountId
     * @param  mixed  $prefundedAccountId
     * @param  ?string  $bridgeWalletId
     * @param  mixed  $destinationWireMessage
     * @param  mixed  $destinationSepaReference
     * @param  ?string  $destinationAchReference
     * @param  ?string  $destinationSpeiReference
     * @param  ?string  $destinationReference
     * @param  ?string  $destinationAddress
     * @param  ?string  $destinationBlockchainMemo
     * @param  ?string  $returnAddress
     * @param  ?string  $address
     * @param  ?string  $state
     * @param  ?string  $customDeveloperFeePercent
     * @phpstan-pure
     */
    public function __construct(LiquidationAddressSourceCurrency $currency, LiquidationAddressSourceChain $chain, mixed $destinationPaymentRail, mixed $destinationCurrency, mixed $externalAccountId = null, mixed $prefundedAccountId = null, ?string $bridgeWalletId = null, mixed $destinationWireMessage = null, mixed $destinationSepaReference = null, ?string $destinationAchReference = null, ?string $destinationSpeiReference = null, ?string $destinationReference = null, ?string $destinationAddress = null, ?string $destinationBlockchainMemo = null, ?string $returnAddress = null, ?string $address = null, ?string $state = null, ?string $customDeveloperFeePercent = null)
    {
        $this->currency = $currency;
        $this->chain = $chain;
        $this->destinationPaymentRail = $destinationPaymentRail;
        $this->destinationCurrency = $destinationCurrency;
        $this->externalAccountId = $externalAccountId;
        $this->prefundedAccountId = $prefundedAccountId;
        $this->bridgeWalletId = $bridgeWalletId;
        $this->destinationWireMessage = $destinationWireMessage;
        $this->destinationSepaReference = $destinationSepaReference;
        $this->destinationAchReference = $destinationAchReference;
        $this->destinationSpeiReference = $destinationSpeiReference;
        $this->destinationReference = $destinationReference;
        $this->destinationAddress = $destinationAddress;
        $this->destinationBlockchainMemo = $destinationBlockchainMemo;
        $this->returnAddress = $returnAddress;
        $this->address = $address;
        $this->state = $state;
        $this->customDeveloperFeePercent = $customDeveloperFeePercent;
    }
}