<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


/** How the business is legally registered */
enum CreateBusinessCustomerPayloadBusinessType: string
{
    case Cooperative = 'cooperative';
    case Corporation = 'corporation';
    case Llc = 'llc';
    case Other = 'other';
    case Partnership = 'partnership';
    case SoleProp = 'sole_prop';
    case Trust = 'trust';
}
