<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


class CryptoReturnPolicy
{
    /**
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     *
     * @var ?string $developerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('developer_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $developerId = null;

    /**
     *
     * @var ?string $refundDestinationAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('refund_destination_address')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $refundDestinationAddress = null;

    /**
     *
     * @var ?string $refundDestinationBlockchainMemo
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('refund_destination_blockchain_memo')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $refundDestinationBlockchainMemo = null;

    /**
     *
     * @var ?string $refundDestinationChain
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('refund_destination_chain')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $refundDestinationChain = null;

    /**
     *
     * @var ?string $refundDestinationCurrency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('refund_destination_currency')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $refundDestinationCurrency = null;

    /**
     *
     * @var ?string $strategy
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('strategy')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $strategy = null;

    /**
     * @param  ?string  $id
     * @param  ?string  $developerId
     * @param  ?string  $refundDestinationAddress
     * @param  ?string  $refundDestinationBlockchainMemo
     * @param  ?string  $refundDestinationChain
     * @param  ?string  $refundDestinationCurrency
     * @param  ?string  $strategy
     * @phpstan-pure
     */
    public function __construct(?string $id = null, ?string $developerId = null, ?string $refundDestinationAddress = null, ?string $refundDestinationBlockchainMemo = null, ?string $refundDestinationChain = null, ?string $refundDestinationCurrency = null, ?string $strategy = null)
    {
        $this->id = $id;
        $this->developerId = $developerId;
        $this->refundDestinationAddress = $refundDestinationAddress;
        $this->refundDestinationBlockchainMemo = $refundDestinationBlockchainMemo;
        $this->refundDestinationChain = $refundDestinationChain;
        $this->refundDestinationCurrency = $refundDestinationCurrency;
        $this->strategy = $strategy;
    }
}