<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


class Customer
{
    /**
     * A UUID that uniquely identifies a resource
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     *
     * @var ?string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('first_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $firstName = null;

    /**
     *
     * @var ?string $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('last_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $lastName = null;

    /**
     *
     * @var ?string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $email = null;

    /**
     * `offboarded`: represents a customer's account that was internally reviewed and closed due to suspicious activity.
     *
     * `paused`: represents a customer's account that is currently under review because of activity on the platform.
     *
     *
     * @var ?CustomerStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\CustomerStatus|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CustomerStatus $status = null;

    /**
     *
     * @var ?Capabilities $capabilities
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('capabilities')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\Capabilities|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Capabilities $capabilities = null;

    /**
     * Information about requirements that may be needed in the future for the customer (eg. enhanced KYC checks for high volume transactions etc.). Please consult our KYC guide on how to resolve each requirement.
     *
     * @var ?array<FutureRequirementsDue> $futureRequirementsDue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('future_requirements_due')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\ReThink\BridgeSDK\Models\Components\FutureRequirementsDue>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $futureRequirementsDue = null;

    /**
     * KYC requirements still needed to be completed. Please consult our KYC guide on how to resolve each requirement.
     *
     * @var ?array<RequirementsDue> $requirementsDue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('requirements_due')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\ReThink\BridgeSDK\Models\Components\RequirementsDue>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $requirementsDue = null;

    /**
     * Time of creation of the customer
     *
     * @var ?\DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdAt = null;

    /**
     * Time of last update of the customer
     *
     * @var ?\DateTime $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updated_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $updatedAt = null;

    /**
     * Reasons why a customer KYC was rejected
     *
     * @var ?array<RejectionReason> $rejectionReasons
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('rejection_reasons')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\ReThink\BridgeSDK\Models\Components\RejectionReason>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $rejectionReasons = null;

    /**
     * Whether the customer has accepted the terms of service.
     *
     * @var ?bool $hasAcceptedTermsOfService
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('has_accepted_terms_of_service')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $hasAcceptedTermsOfService = null;

    /**
     * A summary of whether the customer has received approvals to complete onboarding or use certain products/services offered by Bridge.
     *
     * @var ?array<Endorsement> $endorsements
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('endorsements')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\ReThink\BridgeSDK\Models\Components\Endorsement>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $endorsements = null;

    /**
     * @param  ?string  $id
     * @param  ?string  $firstName
     * @param  ?string  $lastName
     * @param  ?string  $email
     * @param  ?CustomerStatus  $status
     * @param  ?Capabilities  $capabilities
     * @param  ?array<FutureRequirementsDue>  $futureRequirementsDue
     * @param  ?array<RequirementsDue>  $requirementsDue
     * @param  ?\DateTime  $createdAt
     * @param  ?\DateTime  $updatedAt
     * @param  ?array<RejectionReason>  $rejectionReasons
     * @param  ?bool  $hasAcceptedTermsOfService
     * @param  ?array<Endorsement>  $endorsements
     * @phpstan-pure
     */
    public function __construct(?string $id = null, ?string $firstName = null, ?string $lastName = null, ?string $email = null, ?CustomerStatus $status = null, ?Capabilities $capabilities = null, ?array $futureRequirementsDue = null, ?array $requirementsDue = null, ?\DateTime $createdAt = null, ?\DateTime $updatedAt = null, ?array $rejectionReasons = null, ?bool $hasAcceptedTermsOfService = null, ?array $endorsements = null)
    {
        $this->id = $id;
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->email = $email;
        $this->status = $status;
        $this->capabilities = $capabilities;
        $this->futureRequirementsDue = $futureRequirementsDue;
        $this->requirementsDue = $requirementsDue;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->rejectionReasons = $rejectionReasons;
        $this->hasAcceptedTermsOfService = $hasAcceptedTermsOfService;
        $this->endorsements = $endorsements;
    }
}