<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


class CustomerRewardHistory
{
    /**
     * The customer ID of the customer
     *
     * @var ?string $customerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customer_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $customerId = null;

    /**
     * The rewards of the customer in the given stablecoin
     *
     * @var ?array<Reward> $rewards
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('rewards')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\ReThink\BridgeSDK\Models\Components\Reward>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $rewards = null;

    /**
     * @param  ?string  $customerId
     * @param  ?array<Reward>  $rewards
     * @phpstan-pure
     */
    public function __construct(?string $customerId = null, ?array $rewards = null)
    {
        $this->customerId = $customerId;
        $this->rewards = $rewards;
    }
}