<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


class Data
{
    /**
     * Amount of the transaction, represented as a dollar denominated string. Examples include "100.25", "0.1", "1.234567", "1.01" etc.
     *
     * @var ?string $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $amount = null;

    /**
     * The fee, expressed as a decimal string, represents the amount you wish to reserve for your own account. This fee is the final amount deducted from what your customer ultimately receives, rather than a percentage.\n\nIt is denominated in the source currency if that is a fiat currency, or in the fiat currency to which the source currency is pegged.
     *
     * @var ?string $developerFee
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('developer_fee')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $developerFee = null;

    /**
     *
     * @var ?\DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdAt = null;

    /**
     *
     * @var ?\DateTime $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updated_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $updatedAt = null;

    /**
     * A UUID that uniquely identifies a resource
     *
     * @var ?string $customerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customer_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $customerId = null;

    /**
     *
     * @var ?BridgeWalletHistorySource $source
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\BridgeWalletHistorySource|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?BridgeWalletHistorySource $source = null;

    /**
     *
     * @var ?BridgeWalletHistoryDestination $destination
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('destination')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\BridgeWalletHistoryDestination|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?BridgeWalletHistoryDestination $destination = null;

    /**
     * @param  ?string  $amount
     * @param  ?string  $developerFee
     * @param  ?\DateTime  $createdAt
     * @param  ?\DateTime  $updatedAt
     * @param  ?string  $customerId
     * @param  ?BridgeWalletHistorySource  $source
     * @param  ?BridgeWalletHistoryDestination  $destination
     * @phpstan-pure
     */
    public function __construct(?string $amount = null, ?string $developerFee = null, ?\DateTime $createdAt = null, ?\DateTime $updatedAt = null, ?string $customerId = null, ?BridgeWalletHistorySource $source = null, ?BridgeWalletHistoryDestination $destination = null)
    {
        $this->amount = $amount;
        $this->developerFee = $developerFee;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->customerId = $customerId;
        $this->source = $source;
        $this->destination = $destination;
    }
}