<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


class Details
{
    /**
     * ID in the vendor system used to identify this authorized card transaction
     *
     * @var ?string $vendorAuthId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('vendor_auth_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $vendorAuthId = null;

    /**
     * @param  ?string  $vendorAuthId
     * @phpstan-pure
     */
    public function __construct(?string $vendorAuthId = null)
    {
        $this->vendorAuthId = $vendorAuthId;
    }
}