<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


class DrainReceipt
{
    /**
     * The initial amount of the drain, denominated in the fiat currency to which the currency of the Liquidation Address is pegged. Examples include "100.25", "0.1", "1.234567", "1.000000000000000001" etc.
     *
     * @var string $initialAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('initial_amount')]
    public string $initialAmount;

    /**
     * The developer fee, denominated in the fiat currency to which the currency of the Liquidation Address is pegged. This fee is a specific amount deducted from the initial total before conversion, rather than a percentage.
     *
     * @var string $developerFee
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('developer_fee')]
    public string $developerFee;

    /**
     * The initial amount of the drain less the `developer_fee`, denominated in the fiat currency to which the Liquidation Address currency is pegged. Examples include "100.25", "0.1", "1.234567", "1.000000000000000001" etc.
     *
     * @var string $subtotalAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subtotal_amount')]
    public string $subtotalAmount;

    /**
     * The converted amount of the drain. It's denominated in the destination currency or its pegged fiat currency.
     *
     * @var string $convertedAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('converted_amount')]
    public string $convertedAmount;

    /**
     * The effective exchange rate that can be calculated by dividing the converted amount by the amount available for conversion after deducting the developer fee.
     *
     * @var mixed $exchangeRate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('exchange_rate')]
    #[\Speakeasy\Serializer\Annotation\Type('mixed')]
    public mixed $exchangeRate;

    /**
     * The final amount of the drain, equal to the `converted_amount` minus any gas fees. It's denominated in the destination currency or its pegged fiat currency.
     *
     * @var string $outgoingAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('outgoing_amount')]
    public string $outgoingAmount;

    /**
     *
     * @var Currency $destinationCurrency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('destination_currency')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\Currency')]
    public Currency $destinationCurrency;

    /**
     * The fee that is deducted from the withdrawn amount to pay for gas.  Only included for crypto withdrawals that cost gas (e.g. USDT or DAI). It's denominated in the fiat currency to which the destination currency is pegged.
     *
     * @var ?string $gasFee
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('gas_fee')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $gasFee = null;

    /**
     * The URL of a user-facing copy of the receipt.
     *
     * @var ?string $url
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $url = null;

    /**
     * @param  string  $initialAmount
     * @param  string  $developerFee
     * @param  string  $subtotalAmount
     * @param  string  $convertedAmount
     * @param  mixed  $exchangeRate
     * @param  string  $outgoingAmount
     * @param  Currency  $destinationCurrency
     * @param  ?string  $gasFee
     * @param  ?string  $url
     * @phpstan-pure
     */
    public function __construct(string $initialAmount, string $developerFee, string $subtotalAmount, string $convertedAmount, mixed $exchangeRate, string $outgoingAmount, Currency $destinationCurrency, ?string $gasFee = null, ?string $url = null)
    {
        $this->initialAmount = $initialAmount;
        $this->developerFee = $developerFee;
        $this->subtotalAmount = $subtotalAmount;
        $this->convertedAmount = $convertedAmount;
        $this->exchangeRate = $exchangeRate;
        $this->outgoingAmount = $outgoingAmount;
        $this->destinationCurrency = $destinationCurrency;
        $this->gasFee = $gasFee;
        $this->url = $url;
    }
}