<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


class Drain
{
    /**
     * A UUID that uniquely identifies a resource
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Amount of the drain, represented as a dollar denominated string. Examples include "100.25", "0.1", "1.234567", "1.01" etc.
     *
     * @var string $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    public string $amount;

    /**
     * A UUID that uniquely identifies a resource
     *
     * @var string $customerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customer_id')]
    public string $customerId;

    /**
     * A UUID that uniquely identifies a resource
     *
     * @var string $liquidationAddressId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('liquidation_address_id')]
    public string $liquidationAddressId;

    /**
     *
     * @var EuroInclusiveCurrency $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\EuroInclusiveCurrency')]
    public EuroInclusiveCurrency $currency;

    /**
     *
     * @var TransactionStatus $state
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('state')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\TransactionStatus')]
    public TransactionStatus $state;

    /**
     * Time of creation of the drain
     *
     * @var ?\DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdAt = null;

    /**
     * Time of last update of the drain
     *
     * @var ?\DateTime $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updated_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $updatedAt = null;

    /**
     * Hash of the Liquidation Address deposit that triggered this drain
     *
     * @var ?string $depositTxHash
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('deposit_tx_hash')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $depositTxHash = null;

    /**
     * The blockchain address that sent funds to the Liquidation Address
     *
     * @var ?string $fromAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('from_address')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $fromAddress = null;

    /**
     * The source payment rail where the funds originated from
     *
     * @var ?string $sourcePaymentRail
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_payment_rail')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $sourcePaymentRail = null;

    /**
     *
     * @var ?DrainDestination $destination
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('destination')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\DrainDestination|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?DrainDestination $destination = null;

    /**
     * Hash of withdrawal of funds to the destination
     *
     * @var ?string $destinationTxHash
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('destination_tx_hash')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $destinationTxHash = null;

    /**
     * Hash of refund, if the drain has been returned
     *
     * @var ?string $refundTxHash
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('refund_tx_hash')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $refundTxHash = null;

    /**
     *
     * @var ?DrainReturnDetails $returnDetails
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('return_details')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\DrainReturnDetails|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?DrainReturnDetails $returnDetails = null;

    /**
     *
     * @var ?DrainReceipt $receipt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('receipt')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\DrainReceipt|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?DrainReceipt $receipt = null;

    /**
     * @param  string  $id
     * @param  string  $amount
     * @param  string  $customerId
     * @param  string  $liquidationAddressId
     * @param  EuroInclusiveCurrency  $currency
     * @param  TransactionStatus  $state
     * @param  ?\DateTime  $createdAt
     * @param  ?\DateTime  $updatedAt
     * @param  ?string  $depositTxHash
     * @param  ?string  $fromAddress
     * @param  ?string  $sourcePaymentRail
     * @param  ?DrainDestination  $destination
     * @param  ?string  $destinationTxHash
     * @param  ?string  $refundTxHash
     * @param  ?DrainReturnDetails  $returnDetails
     * @param  ?DrainReceipt  $receipt
     * @phpstan-pure
     */
    public function __construct(string $id, string $amount, string $customerId, string $liquidationAddressId, EuroInclusiveCurrency $currency, TransactionStatus $state, ?\DateTime $createdAt = null, ?\DateTime $updatedAt = null, ?string $depositTxHash = null, ?string $fromAddress = null, ?string $sourcePaymentRail = null, ?DrainDestination $destination = null, ?string $destinationTxHash = null, ?string $refundTxHash = null, ?DrainReturnDetails $returnDetails = null, ?DrainReceipt $receipt = null)
    {
        $this->id = $id;
        $this->amount = $amount;
        $this->customerId = $customerId;
        $this->liquidationAddressId = $liquidationAddressId;
        $this->currency = $currency;
        $this->state = $state;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->depositTxHash = $depositTxHash;
        $this->fromAddress = $fromAddress;
        $this->sourcePaymentRail = $sourcePaymentRail;
        $this->destination = $destination;
        $this->destinationTxHash = $destinationTxHash;
        $this->refundTxHash = $refundTxHash;
        $this->returnDetails = $returnDetails;
        $this->receipt = $receipt;
    }
}