<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


class DrainReturnDetails
{
    /**
     * The reason for the return, as given by the returning financial institution.
     *
     * @var ?string $reason
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('reason')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $reason = null;

    /**
     * If the return is due to a risk rejection, this field will be populated with the reason for the risk rejection.
     *
     * @var ?string $riskRejectionReason
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('risk_rejection_reason')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $riskRejectionReason = null;

    /**
     * @param  ?string  $reason
     * @param  ?string  $riskRejectionReason
     * @phpstan-pure
     */
    public function __construct(?string $reason = null, ?string $riskRejectionReason = null)
    {
        $this->reason = $reason;
        $this->riskRejectionReason = $riskRejectionReason;
    }
}