<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


/** The type of endorsement. */
enum EndorsementType: string
{
    case Base = 'base';
    case Cards = 'cards';
    case FasterPayments = 'faster_payments';
    case Pix = 'pix';
    case Sepa = 'sepa';
    case Spei = 'spei';
}
