<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


enum EuroInclusiveFiatCurrency: string
{
    case Usd = 'usd';
    case Eur = 'eur';
    case Mxn = 'mxn';
    case Brl = 'brl';
    case Gbp = 'gbp';
}
