<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


enum EventTypeParameter: string
{
    case FundsReceived = 'funds_received';
    case PaymentSubmitted = 'payment_submitted';
    case PaymentProcessed = 'payment_processed';
    case InReview = 'in_review';
    case Refund = 'refund';
    case Microdeposit = 'microdeposit';
    case AccountUpdate = 'account_update';
    case Deactivation = 'deactivation';
    case Activation = 'activation';
}
