<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


enum EventObjectStatus: string
{
    case NotStarted = 'not_started';
    case Incomplete = 'incomplete';
    case Active = 'active';
    case Rejected = 'rejected';
    case UnderReview = 'under_review';
    case ManualReview = 'manual_review';
    case AwaitingUbo = 'awaiting_ubo';
    case Approved = 'approved';
    case AwaitingFunds = 'awaiting_funds';
    case FundsReceived = 'funds_received';
    case PaymentSubmitted = 'payment_submitted';
    case PaymentProcessed = 'payment_processed';
    case InReview = 'in_review';
    case Canceled = 'canceled';
    case Error = 'error';
    case Returned = 'returned';
    case Refunded = 'refunded';
    case Undeliverable = 'undeliverable';
}
