<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


/** The values here will be prefixed with the event_category. For example, a customer created event will be `customer.created` */
enum EventType: string
{
    case Created = 'created';
    case Updated = 'updated';
    case UpdatedStatusTransitioned = 'updated.status_transitioned';
    case Deleted = 'deleted';
    case Canceled = 'canceled';
}
