<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


class FiatPayoutConfigurationResponse
{
    /**
     * A nested hash structure representing the fiat payout configuration. The top-level keys are currency codes. 
     *
     * Each currency maps to a hash where keys are payment rail codes and values are payout names.
     *
     *
     * @var FiatPayoutConfiguration $fiatPayoutConfiguration
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('fiat_payout_configuration')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\FiatPayoutConfiguration')]
    public FiatPayoutConfiguration $fiatPayoutConfiguration;

    /**
     * @param  FiatPayoutConfiguration  $fiatPayoutConfiguration
     * @phpstan-pure
     */
    public function __construct(FiatPayoutConfiguration $fiatPayoutConfiguration)
    {
        $this->fiatPayoutConfiguration = $fiatPayoutConfiguration;
    }
}