<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


/**
 * The `type` provided determines whether you are submitting a tax identification number or some form of government-issued ID.
 *
 *
 * Reference these lists for tax identification numbers by country: [Individuals](https://apidocs.bridge.xyz/docs/individual-tax-identification-numbers-by-country), [Businesses](https://apidocs.bridge.xyz/docs/business-tax-identification-numbers-by-country)
 *
 * Here is the list of acceptable government issued id documents: `drivers_license`, `matriculate_id`, `military_id`, `permanent_residency_id`, `state_or_provincial_id`, `visa`, `national_id`, `passport`
 *
 * All customers must provide at least one Tax Identification Number for their issuing country. If a country cannot be found, please select `other` and ensure the `description` field is provided.
 *
 * Non-U.S. `individual` customers and associated persons must include a combination of at least one Tax Identification Number and at least one photo id document such as a `passport` (with `image_front`) or a government-issued `drivers_license`. If the photo id document used is also a valid tax identification number (like a national id), it can be submitted as a single object in the `identifying_information` array; otherwise, a valid tax identification number must also be submitted as a separate object in the `identifying_information` array.
 *
 */
enum IdentifyingInformationType: string
{
    case DriversLicense = 'drivers_license';
    case MatriculateId = 'matriculate_id';
    case MilitaryId = 'military_id';
    case NationalId = 'national_id';
    case Passport = 'passport';
    case PermanentResidencyId = 'permanent_residency_id';
    case StateOrProvincialId = 'state_or_provincial_id';
    case Visa = 'visa';
    case Abn = 'abn';
    case Acn = 'acn';
    case Ahv = 'ahv';
    case Ak = 'ak';
    case Aom = 'aom';
    case Arbn = 'arbn';
    case Avs = 'avs';
    case Bc = 'bc';
    case Bce = 'bce';
    case Bin = 'bin';
    case Bir = 'bir';
    case Bp = 'bp';
    case Brn = 'brn';
    case Bsn = 'bsn';
    case Bvn = 'bvn';
    case Cc = 'cc';
    case Cdi = 'cdi';
    case CedulaJuridica = 'cedula_juridica';
    case Cf = 'cf';
    case Cif = 'cif';
    case Cin = 'cin';
    case Cipc = 'cipc';
    case Cn = 'cn';
    case Cnp = 'cnp';
    case Cnpj = 'cnpj';
    case Cpf = 'cpf';
    case Cpr = 'cpr';
    case Crc = 'crc';
    case Crib = 'crib';
    case Crn = 'crn';
    case Cro = 'cro';
    case Cui = 'cui';
    case Cuil = 'cuil';
    case Curp = 'curp';
    case Cuit = 'cuit';
    case Cvr = 'cvr';
    case Edrpou = 'edrpou';
    case Ein = 'ein';
    case Embg = 'embg';
    case EmiratesId = 'emirates_id';
    case En = 'en';
    case Fin = 'fin';
    case Fn = 'fn';
    case Gstin = 'gstin';
    case Gui = 'gui';
    case Hetu = 'hetu';
    case Hkid = 'hkid';
    case Hn = 'hn';
    case Ic = 'ic';
    case Ico = 'ico';
    case Id = 'id';
    case IdBroj = 'id_broj';
    case Idno = 'idno';
    case Idnp = 'idnp';
    case Idnr = 'idnr';
    case If = 'if';
    case Iin = 'iin';
    case Ik = 'ik';
    case Inn = 'inn';
    case Ird = 'ird';
    case Itin = 'itin';
    case Itr = 'itr';
    case Iva = 'iva';
    case Jmbg = 'jmbg';
    case Kbo = 'kbo';
    case Kvk = 'kvk';
    case Matricule = 'matricule';
    case Mf = 'mf';
    case Mn = 'mn';
    case Ms = 'ms';
    case Mst = 'mst';
    case Nic = 'nic';
    case Nicn = 'nicn';
    case Nie = 'nie';
    case Nif = 'nif';
    case Nin = 'nin';
    case Nino = 'nino';
    case Nip = 'nip';
    case Nipc = 'nipc';
    case Nipt = 'nipt';
    case Nit = 'nit';
    case Npwp = 'npwp';
    case Nric = 'nric';
    case Nrn = 'nrn';
    case Nrt = 'nrt';
    case Ntn = 'ntn';
    case Nuit = 'nuit';
    case Nzbn = 'nzbn';
    case Oib = 'oib';
    case Orgnr = 'orgnr';
    case Other = 'other';
    case Pan = 'pan';
    case PartitaIva = 'partita_iva';
    case Pesel = 'pesel';
    case Pib = 'pib';
    case Pin = 'pin';
    case Pk = 'pk';
    case Ppsn = 'ppsn';
    case Qid = 'qid';
    case Rc = 'rc';
    case Regon = 'regon';
    case Rfc = 'rfc';
    case Ricn = 'ricn';
    case Rif = 'rif';
    case Rn = 'rn';
    case Rnc = 'rnc';
    case Rnokpp = 'rnokpp';
    case Rp = 'rp';
    case Rrn = 'rrn';
    case Rtn = 'rtn';
    case Ruc = 'ruc';
    case Rut = 'rut';
    case Si = 'si';
    case Sin = 'sin';
    case Siren = 'siren';
    case Siret = 'siret';
    case Spi = 'spi';
    case Ssm = 'ssm';
    case Ssn = 'ssn';
    case SteuerId = 'steuer_id';
    case Strn = 'strn';
    case Tckn = 'tckn';
    case Tfn = 'tfn';
    case Tin = 'tin';
    case Tpin = 'tpin';
    case Trn = 'trn';
    case Ucn = 'ucn';
    case Uen = 'uen';
    case Uic = 'uic';
    case Uid = 'uid';
    case Usc = 'usc';
    case UstIdnr = 'ust_idnr';
    case Utr = 'utr';
    case Vat = 'vat';
    case Vkn = 'vkn';
    case Voen = 'voen';
    case YTunnus = 'y_tunnus';
}
