<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


class IdentifyingInformation
{
    /**
     * The `type` provided determines whether you are submitting a tax identification number or some form of government-issued ID.
     *
     *
     * Reference these lists for tax identification numbers by country: [Individuals](https://apidocs.bridge.xyz/docs/individual-tax-identification-numbers-by-country), [Businesses](https://apidocs.bridge.xyz/docs/business-tax-identification-numbers-by-country)
     *
     * Here is the list of acceptable government issued id documents: `drivers_license`, `matriculate_id`, `military_id`, `permanent_residency_id`, `state_or_provincial_id`, `visa`, `national_id`, `passport`
     *
     * All customers must provide at least one Tax Identification Number for their issuing country. If a country cannot be found, please select `other` and ensure the `description` field is provided.
     *
     * Non-U.S. `individual` customers and associated persons must include a combination of at least one Tax Identification Number and at least one photo id document such as a `passport` (with `image_front`) or a government-issued `drivers_license`. If the photo id document used is also a valid tax identification number (like a national id), it can be submitted as a single object in the `identifying_information` array; otherwise, a valid tax identification number must also be submitted as a separate object in the `identifying_information` array.
     *
     *
     * @var IdentifyingInformationType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\IdentifyingInformationType')]
    public IdentifyingInformationType $type;

    /**
     * The ISO 3166-1 (three-character) country code that issued the provided document.
     *
     * @var string $issuingCountry
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('issuing_country')]
    public string $issuingCountry;

    /**
     * The unique identifier of the document. Required if this document is being used as a tax identification number (e.g., you are providing a passport or national_id with no other identification).
     *
     * @var ?string $number
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('number')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $number = null;

    /**
     * A description describing the provided document. This field is required when `other` is selected.
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     * The expiration date of the given document in yyyy-mm-dd format.
     *
     * @var ?string $expiration
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expiration')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $expiration = null;

    /**
     * This field is optionally accepted for tax_id types, but required for government_id types. Base64 encoded image* of the front side of the provided document, following the data-uri scheme i.e. data:image/[type];base64,[base_64_encoded_file_contents], with a minimum size of 200px x 200px \n\n*Maximum File Size: 15MB\n\n*Valid file types: .pdf, .jpeg, .jpg, .png, .heic, .tif
     *
     *
     * _Note: When combined with an `image_back`, the combined size of both images must not exceed 24MB._
     *
     *
     * @var ?string $imageFront
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('image_front')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $imageFront = null;

    /**
     * Base64 encoded image* of the back side of the provided document, following the data-uri scheme i.e. data:image/[type];base64,[base_64_encoded_file_contents], with a minimum size of 200px x 200px \n\n*Maximum File Size: 15MB\n\n*Valid file types: .pdf, .jpeg, .jpg, .png, .heic, .tif
     *
     *
     * _Note: When combined with an `image_front`, the combined size of both images must not exceed 24MB._
     *
     *
     * @var ?string $imageBack
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('image_back')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $imageBack = null;

    /**
     * @param  IdentifyingInformationType  $type
     * @param  string  $issuingCountry
     * @param  ?string  $number
     * @param  ?string  $description
     * @param  ?string  $expiration
     * @param  ?string  $imageFront
     * @param  ?string  $imageBack
     * @phpstan-pure
     */
    public function __construct(IdentifyingInformationType $type, string $issuingCountry, ?string $number = null, ?string $description = null, ?string $expiration = null, ?string $imageFront = null, ?string $imageBack = null)
    {
        $this->type = $type;
        $this->issuingCountry = $issuingCountry;
        $this->number = $number;
        $this->description = $description;
        $this->expiration = $expiration;
        $this->imageFront = $imageFront;
        $this->imageBack = $imageBack;
    }
}