<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


/** Missing - an object that will specify an indepth breakdown of what items are missing for this endorsement. */
class Missing
{

    public function __construct()
    {
    }
}