<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


enum PaymentRail: string
{
    case Ach = 'ach';
    case Wire = 'wire';
    case AchPush = 'ach_push';
    case AchSameDay = 'ach_same_day';
    case Arbitrum = 'arbitrum';
    case AvalancheCChain = 'avalanche_c_chain';
    case Base = 'base';
    case Ethereum = 'ethereum';
    case Optimism = 'optimism';
    case Pix = 'pix';
    case Polygon = 'polygon';
    case Solana = 'solana';
    case Spei = 'spei';
    case Stellar = 'stellar';
}
