<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


/** The current status of the card PIN */
enum PinStatus: string
{
    case NotSet = 'not_set';
    case Ok = 'ok';
}
