<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


/** The payout method to use for BRL PIX transfers */
enum PixEnum: string
{
    case PaymentProvider = 'payment_provider';
}
