<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


class PlaidExchangePublicToken
{
    /**
     * Public token generated via the Plaid Link SDK
     *
     * @var string $publicToken
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('public_token')]
    public string $publicToken;

    /**
     * @param  string  $publicToken
     * @phpstan-pure
     */
    public function __construct(string $publicToken)
    {
        $this->publicToken = $publicToken;
    }
}