<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


class PlaidLinkRequest
{
    /**
     * Link token generated via the Plaid Link SDK
     *
     * @var ?string $linkToken
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('link_token')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $linkToken = null;

    /**
     * Expiration time of the link token
     *
     * @var ?\DateTime $linkTokenExpiresAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('link_token_expires_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $linkTokenExpiresAt = null;

    /**
     * URL to call through Plaid Link Flow's onSuccess callback with the public token passed in the body of the request
     *
     * @var ?string $callbackUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('callback_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $callbackUrl = null;

    /**
     * @param  ?string  $linkToken
     * @param  ?\DateTime  $linkTokenExpiresAt
     * @param  ?string  $callbackUrl
     * @phpstan-pure
     */
    public function __construct(?string $linkToken = null, ?\DateTime $linkTokenExpiresAt = null, ?string $callbackUrl = null)
    {
        $this->linkToken = $linkToken;
        $this->linkTokenExpiresAt = $linkTokenExpiresAt;
        $this->callbackUrl = $callbackUrl;
    }
}