<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


class PostCardPushProvisioningInput
{
    /**
     * The wallet provider of the push provisioning request
     *
     * @var ?CardWalletProvider $walletProvider
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('wallet_provider')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\CardWalletProvider|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CardWalletProvider $walletProvider = null;

    /**
     * Apple Pay specific provisioning request data. Required for `apple_pay` wallet provider.
     *
     * @var ?PostCardPushProvisioningInputApplePay $applePay
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('apple_pay')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\PostCardPushProvisioningInputApplePay|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PostCardPushProvisioningInputApplePay $applePay = null;

    /**
     * Google Pay specific push provisioning request data. Required for `google_pay` wallet provider.
     *
     * @var ?PostCardPushProvisioningInputGooglePay $googlePay
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('google_pay')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\PostCardPushProvisioningInputGooglePay|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PostCardPushProvisioningInputGooglePay $googlePay = null;

    /**
     * @param  ?CardWalletProvider  $walletProvider
     * @param  ?PostCardPushProvisioningInputApplePay  $applePay
     * @param  ?PostCardPushProvisioningInputGooglePay  $googlePay
     * @phpstan-pure
     */
    public function __construct(?CardWalletProvider $walletProvider = null, ?PostCardPushProvisioningInputApplePay $applePay = null, ?PostCardPushProvisioningInputGooglePay $googlePay = null)
    {
        $this->walletProvider = $walletProvider;
        $this->applePay = $applePay;
        $this->googlePay = $googlePay;
    }
}