<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


class PostCardUnfreezeInput
{
    /**
     * The party of the freeze to be removed
     *
     * @var CardFreezeInitiator $initiator
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('initiator')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\CardFreezeInitiator')]
    public CardFreezeInitiator $initiator;

    /**
     * @param  CardFreezeInitiator  $initiator
     * @phpstan-pure
     */
    public function __construct(CardFreezeInitiator $initiator)
    {
        $this->initiator = $initiator;
    }
}