<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


class PostCryptoReturnPoliciesInput
{
    /**
     * The address to which the refund will be sent. Required if the strategy is `static_address`, but must be unset if the strategy is `refund_to_sender`.
     *
     * @var ?string $refundDestinationAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('refund_destination_address')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $refundDestinationAddress = null;

    /**
     * The memo to include with the refund transaction. Must be unset if the strategy is `refund_to_sender`.
     *
     * @var ?string $refundDestinationBlockchainMemo
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('refund_destination_blockchain_memo')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $refundDestinationBlockchainMemo = null;

    /**
     * The blockchain on which the refund will be sent. Required if the strategy is `static_address`, but must be unset if the strategy is `refund_to_sender`.
     *
     * @var ?string $refundDestinationChain
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('refund_destination_chain')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $refundDestinationChain = null;

    /**
     * The currency to which the refund will be sent. Required if the strategy is `static_address`, but must be unset if the strategy is `refund_to_sender`.
     *
     * @var ?string $refundDestinationCurrency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('refund_destination_currency')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $refundDestinationCurrency = null;

    /**
     * The strategy to use for the refund. Can be `refund_to_sender` or `static_address`. We only support multiple policies for `static_address`; different strategies cannot have multiple policies. If multiple `static_address` policies exist, the policy that matches both the currency and chain will be used first. If no such policy is found, the policy that matches only the currency will be used instead.
     *
     * @var ?string $strategy
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('strategy')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $strategy = null;

    /**
     * @param  ?string  $refundDestinationAddress
     * @param  ?string  $refundDestinationBlockchainMemo
     * @param  ?string  $refundDestinationChain
     * @param  ?string  $refundDestinationCurrency
     * @param  ?string  $strategy
     * @phpstan-pure
     */
    public function __construct(?string $refundDestinationAddress = null, ?string $refundDestinationBlockchainMemo = null, ?string $refundDestinationChain = null, ?string $refundDestinationCurrency = null, ?string $strategy = null)
    {
        $this->refundDestinationAddress = $refundDestinationAddress;
        $this->refundDestinationBlockchainMemo = $refundDestinationBlockchainMemo;
        $this->refundDestinationChain = $refundDestinationChain;
        $this->refundDestinationCurrency = $refundDestinationCurrency;
        $this->strategy = $strategy;
    }
}