<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


/** RejectionReason - Reason why the kyc_status was rejected */
class RejectionReason
{
    /**
     * Developer information for why a customer was rejected. Not to be shared with the customer.
     *
     * @var ?string $developerReason
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('developer_reason')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $developerReason = null;

    /**
     * Reason for why a customer was rejected. To be shared with the customer.
     *
     * @var ?string $reason
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('reason')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $reason = null;

    /**
     * Time of creation of the rejection reason
     *
     * @var ?string $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $createdAt = null;

    /**
     * @param  ?string  $developerReason
     * @param  ?string  $reason
     * @param  ?string  $createdAt
     * @phpstan-pure
     */
    public function __construct(?string $developerReason = null, ?string $reason = null, ?string $createdAt = null)
    {
        $this->developerReason = $developerReason;
        $this->reason = $reason;
        $this->createdAt = $createdAt;
    }
}