<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


class SendWebhookPayload
{
    /**
     * The ID of the event that will be delivered to your endpoint
     *
     * @var ?string $eventId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('event_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $eventId = null;

    /**
     * @param  ?string  $eventId
     * @phpstan-pure
     */
    public function __construct(?string $eventId = null)
    {
        $this->eventId = $eventId;
    }
}