<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


/** The payout method to use for EUR SEPA transfers */
enum Sepa: string
{
    case Bridge = 'bridge';
}
