<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


/** SourceDepositInstructions - Some transfers require a deposit to be made by the customer before Bridge can start the process.  Instructions for how to kick off the transfer will be included here.  The deposit must match these instructions exactly, or the transfer will fail. */
class SourceDepositInstructions
{
    /**
     *
     * @var SepaSwiftInclusivePaymentRail $paymentRail
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('payment_rail')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\SepaSwiftInclusivePaymentRail')]
    public SepaSwiftInclusivePaymentRail $paymentRail;

    /**
     * Amount of the deposit, expressed as a decimal string. It's denominated in the source currency if that is a fiat currency, or in the fiat currency to which the source currency is pegged. Examples include "100.25", "0.1", "1.234567", "1.01" etc.
     *
     * @var string $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    public string $amount;

    /**
     *
     * @var EuroInclusiveCurrency $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\EuroInclusiveCurrency')]
    public EuroInclusiveCurrency $currency;

    /**
     * The crypto wallet address that the customer will send funds from, in order to kick off this transfer
     *
     * @var ?string $fromAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('from_address')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $fromAddress = null;

    /**
     * The crypto wallet address the customer will send funds to in order to initiate the payment processing
     *
     * @var ?string $toAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('to_address')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $toAddress = null;

    /**
     * The message that the customer MUST include in their `wire memo/message`, `ach push description`, or `sepa reference`.
     *
     * @var ?string $depositMessage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('deposit_message')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $depositMessage = null;

    /**
     * The name of the bank that the customer should send the deposit to
     *
     * @var ?string $bankName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bank_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $bankName = null;

    /**
     * The address of the bank that the customer should send the deposit to. For SEPA, the country in this address should be used for sending the deposit
     *
     * @var ?string $bankAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bank_address')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $bankAddress = null;

    /**
     * The routing number of the bank that the customer should send the deposit to
     *
     * @var ?string $bankRoutingNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bank_routing_number')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $bankRoutingNumber = null;

    /**
     * The account number of the bank that the customer should send the deposit to
     *
     * @var ?string $bankAccountNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bank_account_number')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $bankAccountNumber = null;

    /**
     * The name of the beneficiary of the bank account that the customer should send the deposit to
     *
     * @var ?string $bankBeneficiaryName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bank_beneficiary_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $bankBeneficiaryName = null;

    /**
     * The address of the beneficiary of the bank account that the customer should send the deposit to
     *
     * @var ?string $bankBeneficiaryAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bank_beneficiary_address')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $bankBeneficiaryAddress = null;

    /**
     * For SEPA, the International Bank Account Number (IBAN) that the customer should use to send the deposit
     *
     * @var ?string $iban
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('iban')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $iban = null;

    /**
     * For SEPA, the Bank Identifier Code (BIC) that the customer should use to send the deposit
     *
     * @var ?string $bic
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bic')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $bic = null;

    /**
     * For SPEI, the CLABE (account number) that the customer should use to send the deposit
     *
     * @var ?string $clabe
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('clabe')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $clabe = null;

    /**
     * For SEPA, the name of the bank account holder that the customer should use to send the deposit
     *
     * @var ?string $accountHolderName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('account_holder_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $accountHolderName = null;

    /**
     * If present, the message that the customer MUST include in their on chain transfer. Only used for memo-based blockchains such as Stellar and Tron
     *
     * @var ?string $blockchainMemo
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('blockchain_memo')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $blockchainMemo = null;

    /**
     * @param  SepaSwiftInclusivePaymentRail  $paymentRail
     * @param  string  $amount
     * @param  EuroInclusiveCurrency  $currency
     * @param  ?string  $fromAddress
     * @param  ?string  $toAddress
     * @param  ?string  $depositMessage
     * @param  ?string  $bankName
     * @param  ?string  $bankAddress
     * @param  ?string  $bankRoutingNumber
     * @param  ?string  $bankAccountNumber
     * @param  ?string  $bankBeneficiaryName
     * @param  ?string  $bankBeneficiaryAddress
     * @param  ?string  $iban
     * @param  ?string  $bic
     * @param  ?string  $clabe
     * @param  ?string  $accountHolderName
     * @param  ?string  $blockchainMemo
     * @phpstan-pure
     */
    public function __construct(SepaSwiftInclusivePaymentRail $paymentRail, string $amount, EuroInclusiveCurrency $currency, ?string $fromAddress = null, ?string $toAddress = null, ?string $depositMessage = null, ?string $bankName = null, ?string $bankAddress = null, ?string $bankRoutingNumber = null, ?string $bankAccountNumber = null, ?string $bankBeneficiaryName = null, ?string $bankBeneficiaryAddress = null, ?string $iban = null, ?string $bic = null, ?string $clabe = null, ?string $accountHolderName = null, ?string $blockchainMemo = null)
    {
        $this->paymentRail = $paymentRail;
        $this->amount = $amount;
        $this->currency = $currency;
        $this->fromAddress = $fromAddress;
        $this->toAddress = $toAddress;
        $this->depositMessage = $depositMessage;
        $this->bankName = $bankName;
        $this->bankAddress = $bankAddress;
        $this->bankRoutingNumber = $bankRoutingNumber;
        $this->bankAccountNumber = $bankAccountNumber;
        $this->bankBeneficiaryName = $bankBeneficiaryName;
        $this->bankBeneficiaryAddress = $bankBeneficiaryAddress;
        $this->iban = $iban;
        $this->bic = $bic;
        $this->clabe = $clabe;
        $this->accountHolderName = $accountHolderName;
        $this->blockchainMemo = $blockchainMemo;
    }
}