<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


class StaticMemoEventSourceDepositInstructions
{
    /**
     * The message that the customer MUST include in their wire memo/message or ach push description
     *
     * @var string $depositMessage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('deposit_message')]
    public string $depositMessage;

    /**
     * @param  string  $depositMessage
     * @phpstan-pure
     */
    public function __construct(string $depositMessage)
    {
        $this->depositMessage = $depositMessage;
    }
}