<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


class Subdivision
{
    /**
     * The name of the subdivision
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * The subdivision code, which can be used in place of the name when interacting with Bridge via API
     *
     * @var string $code
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('code')]
    public string $code;

    /**
     * @param  string  $name
     * @param  string  $code
     * @phpstan-pure
     */
    public function __construct(string $name, string $code)
    {
        $this->name = $name;
        $this->code = $code;
    }
}