<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


/** Use `our` for all charges to be borne by the sender, and `sha` for them to be shared between the sender and receiver. */
enum SwiftCharges: string
{
    case Our = 'our';
    case Sha = 'sha';
}
