<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


class SwiftBankAccountInput
{
    /**
     *
     * @var IbanBankAccountInput|UnknownBankAccountInput $account
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('account')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\IbanBankAccountInput|\ReThink\BridgeSDK\Models\Components\UnknownBankAccountInput')]
    public IbanBankAccountInput|UnknownBankAccountInput $account;

    /**
     *
     * @var Address $address
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('address')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\Address')]
    public Address $address;

    /**
     * The category of the Swift account. Can be `client`, `parent_company`, `subsidiary`, or `supplier`
     *
     * @var string $category
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('category')]
    public string $category;

    /**
     * The nature of the transactions this account will participate in. Can be `intra_group_transfer`, `invoice_for_goods_and_services`
     *
     * @var array<string> $purposeOfFunds
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('purpose_of_funds')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>')]
    public array $purposeOfFunds;

    /**
     * How the business uses the funds
     *
     * @var string $shortBusinessDescription
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('short_business_description')]
    public string $shortBusinessDescription;

    /**
     * @param  IbanBankAccountInput|UnknownBankAccountInput  $account
     * @param  Address  $address
     * @param  string  $category
     * @param  array<string>  $purposeOfFunds
     * @param  string  $shortBusinessDescription
     * @phpstan-pure
     */
    public function __construct(IbanBankAccountInput|UnknownBankAccountInput $account, Address $address, string $category, array $purposeOfFunds, string $shortBusinessDescription)
    {
        $this->account = $account;
        $this->address = $address;
        $this->category = $category;
        $this->purposeOfFunds = $purposeOfFunds;
        $this->shortBusinessDescription = $shortBusinessDescription;
    }
}