<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


/** Status of the TOS flow */
enum TosStatus: string
{
    case Pending = 'pending';
    case Approved = 'approved';
}
