<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


/** TransferResponseDestination - The destination of the transfer, which could be an external bank account, a bridge account, or a crypto wallet address */
class TransferResponseDestination
{
    /**
     *
     * @var EuroInclusiveCurrency $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\EuroInclusiveCurrency')]
    public EuroInclusiveCurrency $currency;

    /**
     *
     * @var SepaSwiftInclusivePaymentRail $paymentRail
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('payment_rail')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\SepaSwiftInclusivePaymentRail')]
    public SepaSwiftInclusivePaymentRail $paymentRail;

    /**
     * A UUID that uniquely identifies a resource
     *
     * @var ?string $externalAccountId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('external_account_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $externalAccountId = null;

    /**
     * A UUID that uniquely identifies a resource
     *
     * @var ?string $bridgeWalletId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bridge_wallet_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $bridgeWalletId = null;

    /**
     * (Wire only) The OMAD of a wire transfer, if available
     *
     * @var ?string $omad
     * @deprecated  field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('omad')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $omad = null;

    /**
     * (Wire only) The IMAD of a wire transfer, if available
     *
     * @var ?string $imad
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('imad')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $imad = null;

    /**
     * The trace number of an ACH transfer
     *
     * @var ?string $traceNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('trace_number')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $traceNumber = null;

    /**
     * A message to be sent with a wire transfer, only allowed when the payment rail is a wire.  This message will be validated against 4 lines, each with a max length of 35 char according to the Fedwire standard.
     *
     * @var ?string $wireMessage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('wire_message')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $wireMessage = null;

    /**
     * A reference message to be sent with a SEPA transaction. We recommend you set a unique value to help you and your customers track payments end to end. It must be from 6 to 140 characters. The allowed characters are `a-z`, `A-Z`, `0-9`, spaces, ampersand (`&`), hyphen (`-`), full stop (`.`), and solidus (`/`). If not populated, the default value is "Payment via Bridge {unique_token}".
     *
     * @var ?string $sepaReference
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sepa_reference')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $sepaReference = null;

    /**
     * A payment reference message or remittance information to be included in a SWIFT transaction. It can have at most 4 lines (separated by "\n"), each line with a max length of 35 chars. The allowed characters are `a-z`, `A-Z`, `0-9`, special characters (`/` `-` `?` `:` `(` `)` `.` `,` `'` `+`), and space
     *
     * @var ?string $swiftReference
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('swift_reference')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $swiftReference = null;

    /**
     * A payment reference message or remittance information to be included in a SPEI transaction. The allowed characters are alphanumeric `a-z`, `A-Z`, `0-9`, and space
     *
     * @var ?string $speiReference
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('spei_reference')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $speiReference = null;

    /**
     * A payment reference message for newer payment rails (e.g. Pix and Faster Payments).
     *
     *
     *
     * @var ?string $reference
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('reference')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $reference = null;

    /**
     * Use `our` for all charges to be borne by the sender, and `sha` for them to be shared between the sender and receiver.
     *
     * @var ?SwiftCharges $swiftCharges
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('swift_charges')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\SwiftCharges|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?SwiftCharges $swiftCharges = null;

    /**
     * A reference message to be sent with an ACH transaction. It can be at most 10 characters, A-Z, a-z, 0-9, and spaces.
     *
     * @var ?string $achReference
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ach_reference')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $achReference = null;

    /**
     * The UETR of this SEPA transaction, for tracing purposes.
     *
     * @var ?string $uetr
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('uetr')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $uetr = null;

    /**
     * A message to be sent with a crypto transaction, only allowed when the payment rail is Stellar.
     *
     * @var ?string $blockchainMemo
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('blockchain_memo')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $blockchainMemo = null;

    /**
     * A UUID that uniquely identifies a deposit
     *
     * @var ?string $depositId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('deposit_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $depositId = null;

    /**
     * The clave de rastreo or tracking number of a SPEI transaction
     *
     * @var ?string $trackingNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tracking_number')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $trackingNumber = null;

    /**
     * The unique transaction identifier for a Pix transaction
     *
     * @var ?string $transactionId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transaction_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $transactionId = null;

    /**
     * The name of the institution sending the funds
     *
     * @var ?string $sendingInstitutionName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sending_institution_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $sendingInstitutionName = null;

    /**
     * The crypto wallet address that the customer wishes to ultimately receive funds at, in order to complete this transfer
     *
     * @var ?string $toAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('to_address')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $toAddress = null;

    /**
     * @param  EuroInclusiveCurrency  $currency
     * @param  SepaSwiftInclusivePaymentRail  $paymentRail
     * @param  ?string  $externalAccountId
     * @param  ?string  $bridgeWalletId
     * @param  ?string  $omad
     * @param  ?string  $imad
     * @param  ?string  $traceNumber
     * @param  ?string  $wireMessage
     * @param  ?string  $sepaReference
     * @param  ?string  $swiftReference
     * @param  ?string  $speiReference
     * @param  ?string  $reference
     * @param  ?SwiftCharges  $swiftCharges
     * @param  ?string  $achReference
     * @param  ?string  $uetr
     * @param  ?string  $blockchainMemo
     * @param  ?string  $depositId
     * @param  ?string  $trackingNumber
     * @param  ?string  $transactionId
     * @param  ?string  $sendingInstitutionName
     * @param  ?string  $toAddress
     * @phpstan-pure
     */
    public function __construct(EuroInclusiveCurrency $currency, SepaSwiftInclusivePaymentRail $paymentRail, ?string $externalAccountId = null, ?string $bridgeWalletId = null, ?string $omad = null, ?string $imad = null, ?string $traceNumber = null, ?string $wireMessage = null, ?string $sepaReference = null, ?string $swiftReference = null, ?string $speiReference = null, ?string $reference = null, ?SwiftCharges $swiftCharges = null, ?string $achReference = null, ?string $uetr = null, ?string $blockchainMemo = null, ?string $depositId = null, ?string $trackingNumber = null, ?string $transactionId = null, ?string $sendingInstitutionName = null, ?string $toAddress = null)
    {
        $this->currency = $currency;
        $this->paymentRail = $paymentRail;
        $this->externalAccountId = $externalAccountId;
        $this->bridgeWalletId = $bridgeWalletId;
        $this->omad = $omad;
        $this->imad = $imad;
        $this->traceNumber = $traceNumber;
        $this->wireMessage = $wireMessage;
        $this->sepaReference = $sepaReference;
        $this->swiftReference = $swiftReference;
        $this->speiReference = $speiReference;
        $this->reference = $reference;
        $this->swiftCharges = $swiftCharges;
        $this->achReference = $achReference;
        $this->uetr = $uetr;
        $this->blockchainMemo = $blockchainMemo;
        $this->depositId = $depositId;
        $this->trackingNumber = $trackingNumber;
        $this->transactionId = $transactionId;
        $this->sendingInstitutionName = $sendingInstitutionName;
        $this->toAddress = $toAddress;
    }
}