<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


class UnknownBankAccountOutput
{
    /**
     * The Bank Identifier Code (BIC) of the bank account
     *
     * @var string $bic
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bic')]
    public string $bic;

    /**
     * Last 4 digits of the bank account number
     *
     * @var ?string $last4
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('last_4')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $last4 = null;

    /**
     * @param  string  $bic
     * @param  ?string  $last4
     * @phpstan-pure
     */
    public function __construct(string $bic, ?string $last4 = null)
    {
        $this->bic = $bic;
        $this->last4 = $last4;
    }
}