<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


/**
 * What is the primary purpose of the customer's account?
 *
 *
 * _Required for high risk customers. More information found [here](https://apidocs.bridge.xyz/docs/individuals)_
 *
 */
enum UpdateIndividualCustomerPayloadAccountPurpose: string
{
    case CharitableDonations = 'charitable_donations';
    case EcommerceRetailPayments = 'ecommerce_retail_payments';
    case InvestmentPurposes = 'investment_purposes';
    case OperatingACompany = 'operating_a_company';
    case Other = 'other';
    case PaymentsToFriendsOrFamilyAbroad = 'payments_to_friends_or_family_abroad';
    case PersonalOrLivingExpenses = 'personal_or_living_expenses';
    case ProtectWealth = 'protect_wealth';
    case PurchaseGoodsAndServices = 'purchase_goods_and_services';
    case ReceivePaymentForFreelancing = 'receive_payment_for_freelancing';
    case ReceiveSalary = 'receive_salary';
}
