<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


enum UpdateBusinessCustomerPayloadPartialHighRiskActivity: string
{
    case AdultEntertainment = 'adult_entertainment';
    case Gambling = 'gambling';
    case HoldClientFunds = 'hold_client_funds';
    case InvestmentServices = 'investment_services';
    case LendingBanking = 'lending_banking';
    case MarijuanaOrRelatedServices = 'marijuana_or_related_services';
    case MoneyServices = 'money_services';
    case NicotineTobaccoOrRelatedServices = 'nicotine_tobacco_or_related_services';
    case OperateForeignExchangeVirtualCurrenciesBrokerageOtc = 'operate_foreign_exchange_virtual_currencies_brokerage_otc';
    case Pharmaceuticals = 'pharmaceuticals';
    case PreciousMetalsPreciousStonesJewelry = 'precious_metals_precious_stones_jewelry';
    case SafeDepositBoxRentals = 'safe_deposit_box_rentals';
    case ThirdPartyPaymentProcessing = 'third_party_payment_processing';
    case WeaponsFirearmsAndExplosives = 'weapons_firearms_and_explosives';
    case NoneOfTheAbove = 'none_of_the_above';
}
