<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


class UpdateVirtualAccountDestination
{
    /**
     *
     * @var ?CryptoCurrency $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\CryptoCurrency|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CryptoCurrency $currency = null;

    /**
     *
     * @var ?OfframpChain $paymentRail
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('payment_rail')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\OfframpChain|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?OfframpChain $paymentRail = null;

    /**
     * The crypto wallet address that the customer wishes to ultimately receive funds at
     *
     * @var ?string $address
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('address')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $address = null;

    /**
     * The memo to include when sending funds on chain. Only allowed for blockchains that support memos such as Stellar
     *
     * @var ?string $blockchainMemo
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('blockchain_memo')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $blockchainMemo = null;

    /**
     * A UUID that uniquely identifies a resource
     *
     * @var ?string $bridgeWalletId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bridge_wallet_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $bridgeWalletId = null;

    /**
     * @param  ?CryptoCurrency  $currency
     * @param  ?OfframpChain  $paymentRail
     * @param  ?string  $address
     * @param  ?string  $blockchainMemo
     * @param  ?string  $bridgeWalletId
     * @phpstan-pure
     */
    public function __construct(?CryptoCurrency $currency = null, ?OfframpChain $paymentRail = null, ?string $address = null, ?string $blockchainMemo = null, ?string $bridgeWalletId = null)
    {
        $this->currency = $currency;
        $this->paymentRail = $paymentRail;
        $this->address = $address;
        $this->blockchainMemo = $blockchainMemo;
        $this->bridgeWalletId = $bridgeWalletId;
    }
}