<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


/**
 * The individuals source of funds, e.g. government_benefits, investments_loans, salary, etc.
 *
 *
 * _Required for high risk customers. More information found [here](https://apidocs.bridge.xyz/docs/individuals)_
 *
 */
enum UpdateIndividualCustomerPayloadSourceOfFunds: string
{
    case CompanyFunds = 'company_funds';
    case EcommerceReseller = 'ecommerce_reseller';
    case GamblingProceeds = 'gambling_proceeds';
    case Gifts = 'gifts';
    case GovernmentBenefits = 'government_benefits';
    case Inheritance = 'inheritance';
    case InvestmentsLoans = 'investments_loans';
    case PensionRetirement = 'pension_retirement';
    case Salary = 'salary';
    case SaleOfAssetsRealEstate = 'sale_of_assets_real_estate';
    case Savings = 'savings';
    case SomeoneElsesFunds = 'someone_elses_funds';
}
