<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


class UpdateIndividualCustomerPayload
{
    /**
     * Type of the customer (individual vs. business).
     *
     * @var ?UpdateIndividualCustomerPayloadType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\UpdateIndividualCustomerPayloadType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?UpdateIndividualCustomerPayloadType $type = null;

    /**
     * The first name of the individual.
     *
     * @var ?string $firstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('first_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $firstName = null;

    /**
     * The middle name of the individual.
     *
     * @var ?string $middleName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('middle_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $middleName = null;

    /**
     * The last name of the individual.
     *
     * @var ?string $lastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('last_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $lastName = null;

    /**
     * Required when the `first_name` includes any non Latin-1 characters. Acceptable characters - Latin-1 Unicode Character Range: À-ÖØ-ßà-öø-ÿ; Standard Unicode Character Range:  -~
     *
     * @var ?string $transliteratedFirstName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transliterated_first_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $transliteratedFirstName = null;

    /**
     * Required when the `middle_name` includes any non Latin-1 characters. Acceptable characters - Latin-1 Unicode Character Range: À-ÖØ-ßà-öø-ÿ; Standard Unicode Character Range:  -~
     *
     * @var ?string $transliteratedMiddleName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transliterated_middle_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $transliteratedMiddleName = null;

    /**
     * Required when the `last_name` includes any non Latin-1 characters. Acceptable characters - Latin-1 Unicode Character Range: À-ÖØ-ßà-öø-ÿ; Standard Unicode Character Range:  -~
     *
     * @var ?string $transliteratedLastName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transliterated_last_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $transliteratedLastName = null;

    /**
     * The individuals primary email address
     *
     * @var ?string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $email = null;

    /**
     * The individuals primary phone number in format "+12223334444"
     *
     * @var ?string $phone
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('phone')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $phone = null;

    /**
     *
     * @var ?Address2025WinterRefresh $residentialAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('residential_address')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\Address2025WinterRefresh|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Address2025WinterRefresh $residentialAddress = null;

    /**
     *
     * @var ?Address2025WinterRefresh $transliteratedResidentialAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transliterated_residential_address')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\Address2025WinterRefresh|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Address2025WinterRefresh $transliteratedResidentialAddress = null;

    /**
     * Date of birth in format yyyy-mm-dd. Must be at least 18 years old.
     *
     * @var ?string $birthDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('birth_date')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $birthDate = null;

    /**
     * The ID of the signed agreement that the customer completed. You can get a signed agreement id for a _new_ customer by following this guide [here](https://apidocs.bridge.xyz/docs/terms-of-service#tos-acceptance-for-a-new-customer).
     *
     *
     *
     * @var ?string $signedAgreementId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('signed_agreement_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $signedAgreementId = null;

    /**
     * List of endorsements to request for this customer. If omitted, we'll attempt to grant `base` and `sepa`.
     *
     *
     * _`proof_of_address` document is required for `sepa` to be approved_
     *
     *
     * @var ?array<EndorsementType> $endorsements
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('endorsements')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\ReThink\BridgeSDK\Models\Components\EndorsementType>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $endorsements = null;

    /**
     * What is the primary purpose of the customer's account?
     *
     *
     * _Required for high risk customers. More information found [here](https://apidocs.bridge.xyz/docs/individuals)_
     *
     *
     * @var ?UpdateIndividualCustomerPayloadAccountPurpose $accountPurpose
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('account_purpose')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\UpdateIndividualCustomerPayloadAccountPurpose|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?UpdateIndividualCustomerPayloadAccountPurpose $accountPurpose = null;

    /**
     * A supplemental description of the `account_purpose`.
     *
     *
     * _Required if the `account_purpose` is `other`._
     *
     *
     * @var ?string $accountPurposeOther
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('account_purpose_other')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $accountPurposeOther = null;

    /**
     * What is the customer's current employment status?
     *
     *
     * _Required for high risk customers. More information found [here](https://apidocs.bridge.xyz/docs/individuals)_
     *
     *
     * @var ?UpdateIndividualCustomerPayloadEmploymentStatus $employmentStatus
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('employment_status')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\UpdateIndividualCustomerPayloadEmploymentStatus|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?UpdateIndividualCustomerPayloadEmploymentStatus $employmentStatus = null;

    /**
     * What is the expected monthly volume of payments the customer will be sending or receiving?
     *
     *
     * _Required for high risk customers. More information found [here](https://apidocs.bridge.xyz/docs/individuals)_
     *
     *
     * @var ?UpdateIndividualCustomerPayloadExpectedMonthlyPaymentsUsd $expectedMonthlyPaymentsUsd
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expected_monthly_payments_usd')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\UpdateIndividualCustomerPayloadExpectedMonthlyPaymentsUsd|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?UpdateIndividualCustomerPayloadExpectedMonthlyPaymentsUsd $expectedMonthlyPaymentsUsd = null;

    /**
     * Is the customer acting as an intermediary for a third party?
     *
     *
     * _Required for high risk customers. More information found [here](https://apidocs.bridge.xyz/docs/individuals)_
     *
     *
     * @var ?bool $actingAsIntermediary
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('acting_as_intermediary')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $actingAsIntermediary = null;

    /**
     * What is the customer's most recent occupation? Specify the relevant alphanumeric occupation code. See the [list of occupations](https://apidocs.bridge.xyz/page/sof-eu-most-recent-occupation-list) for the complete list of valid occupations and codes. _Required for Restricted countries._
     *
     *
     * _Required for high risk customers. More information found [here](https://apidocs.bridge.xyz/docs/individuals)_
     *
     *
     * @var ?string $mostRecentOccupation
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('most_recent_occupation')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $mostRecentOccupation = null;

    /**
     * The individuals source of funds, e.g. government_benefits, investments_loans, salary, etc.
     *
     *
     * _Required for high risk customers. More information found [here](https://apidocs.bridge.xyz/docs/individuals)_
     *
     *
     * @var ?UpdateIndividualCustomerPayloadSourceOfFunds $sourceOfFunds
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source_of_funds')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\UpdateIndividualCustomerPayloadSourceOfFunds|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?UpdateIndividualCustomerPayloadSourceOfFunds $sourceOfFunds = null;

    /**
     * The ISO 3166-1 (three-character) country code representing the nationality of the customer.
     *
     * @var ?string $nationality
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('nationality')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $nationality = null;

    /**
     * The timestamp for when individual's government ID was successfully verified.
     *
     * @var ?string $verifiedGovidAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('verified_govid_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $verifiedGovidAt = null;

    /**
     * The timestamp for when individual's selfie was successfully verified.
     *
     * @var ?string $verifiedSelfieAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('verified_selfie_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $verifiedSelfieAt = null;

    /**
     * The timestamp for when individual successfully passed customer safety check.
     *
     * @var ?string $completedCustomerSafetyCheckAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('completed_customer_safety_check_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $completedCustomerSafetyCheckAt = null;

    /**
     * $identifyingInformation
     *
     * @var ?array<IdentifyingInformation> $identifyingInformation
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('identifying_information')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\ReThink\BridgeSDK\Models\Components\IdentifyingInformation>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $identifyingInformation = null;

    /**
     * Please click "ADD OBJECT" for more information.
     *
     * @var ?array<IndividualDocuments> $documents
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('documents')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\ReThink\BridgeSDK\Models\Components\IndividualDocuments>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $documents = null;

    /**
     * @param  ?UpdateIndividualCustomerPayloadType  $type
     * @param  ?string  $firstName
     * @param  ?string  $middleName
     * @param  ?string  $lastName
     * @param  ?string  $transliteratedFirstName
     * @param  ?string  $transliteratedMiddleName
     * @param  ?string  $transliteratedLastName
     * @param  ?string  $email
     * @param  ?string  $phone
     * @param  ?Address2025WinterRefresh  $residentialAddress
     * @param  ?Address2025WinterRefresh  $transliteratedResidentialAddress
     * @param  ?string  $birthDate
     * @param  ?string  $signedAgreementId
     * @param  ?array<EndorsementType>  $endorsements
     * @param  ?UpdateIndividualCustomerPayloadAccountPurpose  $accountPurpose
     * @param  ?string  $accountPurposeOther
     * @param  ?UpdateIndividualCustomerPayloadEmploymentStatus  $employmentStatus
     * @param  ?UpdateIndividualCustomerPayloadExpectedMonthlyPaymentsUsd  $expectedMonthlyPaymentsUsd
     * @param  ?bool  $actingAsIntermediary
     * @param  ?string  $mostRecentOccupation
     * @param  ?UpdateIndividualCustomerPayloadSourceOfFunds  $sourceOfFunds
     * @param  ?string  $nationality
     * @param  ?string  $verifiedGovidAt
     * @param  ?string  $verifiedSelfieAt
     * @param  ?string  $completedCustomerSafetyCheckAt
     * @param  ?array<IdentifyingInformation>  $identifyingInformation
     * @param  ?array<IndividualDocuments>  $documents
     * @phpstan-pure
     */
    public function __construct(?UpdateIndividualCustomerPayloadType $type = null, ?string $firstName = null, ?string $middleName = null, ?string $lastName = null, ?string $transliteratedFirstName = null, ?string $transliteratedMiddleName = null, ?string $transliteratedLastName = null, ?string $email = null, ?string $phone = null, ?Address2025WinterRefresh $residentialAddress = null, ?Address2025WinterRefresh $transliteratedResidentialAddress = null, ?string $birthDate = null, ?string $signedAgreementId = null, ?array $endorsements = null, ?UpdateIndividualCustomerPayloadAccountPurpose $accountPurpose = null, ?string $accountPurposeOther = null, ?UpdateIndividualCustomerPayloadEmploymentStatus $employmentStatus = null, ?UpdateIndividualCustomerPayloadExpectedMonthlyPaymentsUsd $expectedMonthlyPaymentsUsd = null, ?bool $actingAsIntermediary = null, ?string $mostRecentOccupation = null, ?UpdateIndividualCustomerPayloadSourceOfFunds $sourceOfFunds = null, ?string $nationality = null, ?string $verifiedGovidAt = null, ?string $verifiedSelfieAt = null, ?string $completedCustomerSafetyCheckAt = null, ?array $identifyingInformation = null, ?array $documents = null)
    {
        $this->type = $type;
        $this->firstName = $firstName;
        $this->middleName = $middleName;
        $this->lastName = $lastName;
        $this->transliteratedFirstName = $transliteratedFirstName;
        $this->transliteratedMiddleName = $transliteratedMiddleName;
        $this->transliteratedLastName = $transliteratedLastName;
        $this->email = $email;
        $this->phone = $phone;
        $this->residentialAddress = $residentialAddress;
        $this->transliteratedResidentialAddress = $transliteratedResidentialAddress;
        $this->birthDate = $birthDate;
        $this->signedAgreementId = $signedAgreementId;
        $this->endorsements = $endorsements;
        $this->accountPurpose = $accountPurpose;
        $this->accountPurposeOther = $accountPurposeOther;
        $this->employmentStatus = $employmentStatus;
        $this->expectedMonthlyPaymentsUsd = $expectedMonthlyPaymentsUsd;
        $this->actingAsIntermediary = $actingAsIntermediary;
        $this->mostRecentOccupation = $mostRecentOccupation;
        $this->sourceOfFunds = $sourceOfFunds;
        $this->nationality = $nationality;
        $this->verifiedGovidAt = $verifiedGovidAt;
        $this->verifiedSelfieAt = $verifiedSelfieAt;
        $this->completedCustomerSafetyCheckAt = $completedCustomerSafetyCheckAt;
        $this->identifyingInformation = $identifyingInformation;
        $this->documents = $documents;
    }
}