<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


class UsBankAccountUpdate
{
    /**
     * Determines whether the US account is treated as checking or savings. All US accounts will be treated as checking by default.
     *
     * @var ?CheckingOrSavingsType $checkingOrSavings
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('checking_or_savings')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\CheckingOrSavingsType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CheckingOrSavingsType $checkingOrSavings = null;

    /**
     * Routing number of your bank account. This field is getting deprecated in favor of the `account.routing_number` field for US accounts.
     *
     * @var ?string $routingNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('routing_number')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $routingNumber = null;

    /**
     * @param  ?CheckingOrSavingsType  $checkingOrSavings
     * @param  ?string  $routingNumber
     * @phpstan-pure
     */
    public function __construct(?CheckingOrSavingsType $checkingOrSavings = null, ?string $routingNumber = null)
    {
        $this->checkingOrSavings = $checkingOrSavings;
        $this->routingNumber = $routingNumber;
    }
}