<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


/** Usd - Payment rail configuration for USD */
class Usd
{
    /**
     * The payout method to use for USD wire transfers
     *
     * @var ?Wire $wire
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('wire')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\Wire|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Wire $wire = null;

    /**
     * The payout method to use for USD ACH transfers
     *
     * @var ?AchEnum $ach
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ach')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\AchEnum|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AchEnum $ach = null;

    /**
     * @param  ?Wire  $wire
     * @param  ?AchEnum  $ach
     * @phpstan-pure
     */
    public function __construct(?Wire $wire = null, ?AchEnum $ach = null)
    {
        $this->wire = $wire;
        $this->ach = $ach;
    }
}