<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


class VirtualAccountBR
{
    /**
     * The BR Code that the customer should send the deposit to
     *
     * @var string $brCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('br_code')]
    public string $brCode;

    /**
     * The name of the account owner that the deposit must be sent to.
     *
     * @var string $accountHolderName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('account_holder_name')]
    public string $accountHolderName;

    /**
     *
     * @var VirtualAccountSourceDepositInstructionsBrCurrency $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\VirtualAccountSourceDepositInstructionsBrCurrency')]
    public VirtualAccountSourceDepositInstructionsBrCurrency $currency;

    /**
     * The payment rails supported by these deposit instructions
     *
     * @var array<VirtualAccountSourceDepositInstructionsBrPaymentRail> $paymentRails
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('payment_rails')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\ReThink\BridgeSDK\Models\Components\VirtualAccountSourceDepositInstructionsBrPaymentRail>')]
    public array $paymentRails;

    /**
     * The name of the bank that the customer should send the deposit to
     *
     * @var string $bankName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bank_name')]
    public string $bankName;

    /**
     * The address of the bank that the customer should send the deposit to
     *
     * @var string $bankAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bank_address')]
    public string $bankAddress;

    /**
     * @param  string  $brCode
     * @param  string  $accountHolderName
     * @param  VirtualAccountSourceDepositInstructionsBrCurrency  $currency
     * @param  array<VirtualAccountSourceDepositInstructionsBrPaymentRail>  $paymentRails
     * @param  string  $bankName
     * @param  string  $bankAddress
     * @phpstan-pure
     */
    public function __construct(string $brCode, string $accountHolderName, VirtualAccountSourceDepositInstructionsBrCurrency $currency, array $paymentRails, string $bankName, string $bankAddress)
    {
        $this->brCode = $brCode;
        $this->accountHolderName = $accountHolderName;
        $this->currency = $currency;
        $this->paymentRails = $paymentRails;
        $this->bankName = $bankName;
        $this->bankAddress = $bankAddress;
    }
}