<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


class VirtualAccountSourceInput
{
    /**
     *
     * @var EuroInclusiveFiatCurrency $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\EuroInclusiveFiatCurrency')]
    public EuroInclusiveFiatCurrency $currency;

    /**
     * @param  EuroInclusiveFiatCurrency  $currency
     * @phpstan-pure
     */
    public function __construct(EuroInclusiveFiatCurrency $currency)
    {
        $this->currency = $currency;
    }
}