<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


class VirtualAccountMX
{
    /**
     * The CLABE (account number) of the account that the customer should send the deposit to
     *
     * @var string $clabe
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('clabe')]
    public string $clabe;

    /**
     * The name of the account owner that the deposit must be sent to.
     *
     * @var string $accountHolderName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('account_holder_name')]
    public string $accountHolderName;

    /**
     *
     * @var VirtualAccountSourceDepositInstructionsMxCurrency $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\VirtualAccountSourceDepositInstructionsMxCurrency')]
    public VirtualAccountSourceDepositInstructionsMxCurrency $currency;

    /**
     * The payment rails supported by these deposit instructions
     *
     * @var array<VirtualAccountSourceDepositInstructionsMxPaymentRail> $paymentRails
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('payment_rails')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\ReThink\BridgeSDK\Models\Components\VirtualAccountSourceDepositInstructionsMxPaymentRail>')]
    public array $paymentRails;

    /**
     * The name of the bank that the customer should send the deposit to
     *
     * @var string $bankName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bank_name')]
    public string $bankName;

    /**
     * The address of the bank that the customer should send the deposit to
     *
     * @var string $bankAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bank_address')]
    public string $bankAddress;

    /**
     * @param  string  $clabe
     * @param  string  $accountHolderName
     * @param  VirtualAccountSourceDepositInstructionsMxCurrency  $currency
     * @param  array<VirtualAccountSourceDepositInstructionsMxPaymentRail>  $paymentRails
     * @param  string  $bankName
     * @param  string  $bankAddress
     * @phpstan-pure
     */
    public function __construct(string $clabe, string $accountHolderName, VirtualAccountSourceDepositInstructionsMxCurrency $currency, array $paymentRails, string $bankName, string $bankAddress)
    {
        $this->clabe = $clabe;
        $this->accountHolderName = $accountHolderName;
        $this->currency = $currency;
        $this->paymentRails = $paymentRails;
        $this->bankName = $bankName;
        $this->bankAddress = $bankAddress;
    }
}