<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


class VirtualAccountUS
{
    /**
     * The account number of the bank that the customer should send the deposit to
     *
     * @var string $bankAccountNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bank_account_number')]
    public string $bankAccountNumber;

    /**
     * The routing number of the bank that the customer should send the deposit to
     *
     * @var string $bankRoutingNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bank_routing_number')]
    public string $bankRoutingNumber;

    /**
     * If available, the name of the beneficiary of the bank account that the customer should send the deposit to
     *
     * @var string $bankBeneficiaryName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bank_beneficiary_name')]
    public string $bankBeneficiaryName;

    /**
     * If available, the address of the beneficiary of the bank account that the customer should send the deposit to
     *
     * @var string $bankBeneficiaryAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bank_beneficiary_address')]
    public string $bankBeneficiaryAddress;

    /**
     *
     * @var VirtualAccountSourceDepositInstructionsUsCurrency $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\VirtualAccountSourceDepositInstructionsUsCurrency')]
    public VirtualAccountSourceDepositInstructionsUsCurrency $currency;

    /**
     * The payment rails supported by these deposit instructions
     *
     * @var array<VirtualAccountSourceDepositInstructionsUsPaymentRail> $paymentRails
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('payment_rails')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\ReThink\BridgeSDK\Models\Components\VirtualAccountSourceDepositInstructionsUsPaymentRail>')]
    public array $paymentRails;

    /**
     * The name of the bank that the customer should send the deposit to
     *
     * @var string $bankName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bank_name')]
    public string $bankName;

    /**
     * The address of the bank that the customer should send the deposit to
     *
     * @var string $bankAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bank_address')]
    public string $bankAddress;

    /**
     *
     * @var ?VirtualAccountSourcePaymentRails $paymentRail
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('payment_rail')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\VirtualAccountSourcePaymentRails|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?VirtualAccountSourcePaymentRails $paymentRail = null;

    /**
     * @param  string  $bankAccountNumber
     * @param  string  $bankRoutingNumber
     * @param  string  $bankBeneficiaryName
     * @param  string  $bankBeneficiaryAddress
     * @param  VirtualAccountSourceDepositInstructionsUsCurrency  $currency
     * @param  array<VirtualAccountSourceDepositInstructionsUsPaymentRail>  $paymentRails
     * @param  string  $bankName
     * @param  string  $bankAddress
     * @param  ?VirtualAccountSourcePaymentRails  $paymentRail
     * @phpstan-pure
     */
    public function __construct(string $bankAccountNumber, string $bankRoutingNumber, string $bankBeneficiaryName, string $bankBeneficiaryAddress, VirtualAccountSourceDepositInstructionsUsCurrency $currency, array $paymentRails, string $bankName, string $bankAddress, ?VirtualAccountSourcePaymentRails $paymentRail = null)
    {
        $this->bankAccountNumber = $bankAccountNumber;
        $this->bankRoutingNumber = $bankRoutingNumber;
        $this->bankBeneficiaryName = $bankBeneficiaryName;
        $this->bankBeneficiaryAddress = $bankBeneficiaryAddress;
        $this->currency = $currency;
        $this->paymentRails = $paymentRails;
        $this->bankName = $bankName;
        $this->bankAddress = $bankAddress;
        $this->paymentRail = $paymentRail;
    }
}