<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


class VirtualAccountEventSource
{
    /**
     *
     * @var VirtualAccountSourcePaymentRails $paymentRail
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('payment_rail')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\VirtualAccountSourcePaymentRails')]
    public VirtualAccountSourcePaymentRails $paymentRail;

    /**
     * (ACH and SPEI only) The description of the deposit that the customer sent
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     * (ACH, SEPA, and SPEI only) The name of the business or individual who initiated the transaction
     *
     * @var ?string $senderName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sender_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $senderName = null;

    /**
     * (ACH only) The routing number of the entity that initiated this ACH transaction
     *
     * @var ?string $senderBankRoutingNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sender_bank_routing_number')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $senderBankRoutingNumber = null;

    /**
     * (ACH only) The unique, a 15-digit number associated with each ACH transaction that is used for tracking and reconciling transactions
     *
     * @var ?string $traceNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('trace_number')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $traceNumber = null;

    /**
     * (Wire only) The routing number of the bank that sent the wire to the Virtual Account
     *
     * @var ?string $bankRoutingNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bank_routing_number')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $bankRoutingNumber = null;

    /**
     * (Wire only) The name of the bank that sent the wire
     *
     * @var ?string $bankName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bank_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $bankName = null;

    /**
     * (Wire only) The beneficiary name of this wire
     *
     * @var ?string $bankBeneficiaryName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bank_beneficiary_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $bankBeneficiaryName = null;

    /**
     * (Wire only) The beneficiary address of this wire
     *
     * @var ?string $bankBeneficiaryAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bank_beneficiary_address')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $bankBeneficiaryAddress = null;

    /**
     * (Wire only) The originator name of this wire
     *
     * @var ?string $originatorName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('originator_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $originatorName = null;

    /**
     * (Wire only) The originator address of this wire
     *
     * @var ?string $originatorAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('originator_address')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $originatorAddress = null;

    /**
     * (Wire only) The memo for this wire
     *
     * @var ?string $wireMessage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('wire_message')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $wireMessage = null;

    /**
     * (Wire only) The IMAD of a wire transfer, if available
     *
     * @var ?string $imad
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('imad')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $imad = null;

    /**
     * (SEPA only) The BIC of the bank that initiated this transaction
     *
     * @var ?string $bic
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bic')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $bic = null;

    /**
     * (SEPA only) The full IBAN of the account that initiated this transaction
     *
     * @var ?string $iban
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('iban')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $iban = null;

    /**
     * (SEPA only) The last 4 digits of the IBAN of the account that initiated this transaction
     *
     * @var ?string $ibanLast4
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('iban_last_4')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $ibanLast4 = null;

    /**
     * (SPEI only) The CLABE (account number) of the account that initiated this transaction
     *
     * @var ?string $clabe
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('clabe')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $clabe = null;

    /**
     * A reference message to be sent with a SEPA transaction. We recommend you set a unique value to help you and your customers track payments end to end. It must be from 6 to 140 characters. The allowed characters are `a-z`, `A-Z`, `0-9`, spaces, ampersand (`&`), hyphen (`-`), full stop (`.`), and solidus (`/`). If not populated, the default value is "Payment via Bridge {unique_token}".
     *
     * @var ?string $reference
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('reference')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $reference = null;

    /**
     * (SPEI only) The clave de rastreo or tracking number of the SPEI transaction
     *
     * @var ?string $trackingNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tracking_number')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $trackingNumber = null;

    /**
     *
     * @var ?PaymentScheme $paymentScheme
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('payment_scheme')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\PaymentScheme|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PaymentScheme $paymentScheme = null;

    /**
     * The UETR of this SEPA transaction, for tracing purposes.
     *
     * @var ?string $uetr
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('uetr')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $uetr = null;

    /**
     * @param  VirtualAccountSourcePaymentRails  $paymentRail
     * @param  ?string  $description
     * @param  ?string  $senderName
     * @param  ?string  $senderBankRoutingNumber
     * @param  ?string  $traceNumber
     * @param  ?string  $bankRoutingNumber
     * @param  ?string  $bankName
     * @param  ?string  $bankBeneficiaryName
     * @param  ?string  $bankBeneficiaryAddress
     * @param  ?string  $originatorName
     * @param  ?string  $originatorAddress
     * @param  ?string  $wireMessage
     * @param  ?string  $imad
     * @param  ?string  $bic
     * @param  ?string  $iban
     * @param  ?string  $ibanLast4
     * @param  ?string  $clabe
     * @param  ?string  $reference
     * @param  ?string  $trackingNumber
     * @param  ?PaymentScheme  $paymentScheme
     * @param  ?string  $uetr
     * @phpstan-pure
     */
    public function __construct(VirtualAccountSourcePaymentRails $paymentRail, ?string $description = null, ?string $senderName = null, ?string $senderBankRoutingNumber = null, ?string $traceNumber = null, ?string $bankRoutingNumber = null, ?string $bankName = null, ?string $bankBeneficiaryName = null, ?string $bankBeneficiaryAddress = null, ?string $originatorName = null, ?string $originatorAddress = null, ?string $wireMessage = null, ?string $imad = null, ?string $bic = null, ?string $iban = null, ?string $ibanLast4 = null, ?string $clabe = null, ?string $reference = null, ?string $trackingNumber = null, ?PaymentScheme $paymentScheme = null, ?string $uetr = null)
    {
        $this->paymentRail = $paymentRail;
        $this->description = $description;
        $this->senderName = $senderName;
        $this->senderBankRoutingNumber = $senderBankRoutingNumber;
        $this->traceNumber = $traceNumber;
        $this->bankRoutingNumber = $bankRoutingNumber;
        $this->bankName = $bankName;
        $this->bankBeneficiaryName = $bankBeneficiaryName;
        $this->bankBeneficiaryAddress = $bankBeneficiaryAddress;
        $this->originatorName = $originatorName;
        $this->originatorAddress = $originatorAddress;
        $this->wireMessage = $wireMessage;
        $this->imad = $imad;
        $this->bic = $bic;
        $this->iban = $iban;
        $this->ibanLast4 = $ibanLast4;
        $this->clabe = $clabe;
        $this->reference = $reference;
        $this->trackingNumber = $trackingNumber;
        $this->paymentScheme = $paymentScheme;
        $this->uetr = $uetr;
    }
}