<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace ReThink\BridgeSDK\Models\Components;


class Webhook
{
    /**
     * An identifier that uniquely identifies the webhook endpoint
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * The URL that the webhook will send events to
     *
     * @var string $url
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('url')]
    public string $url;

    /**
     * The status of the webhook. Only active webhooks will receive events automatically.
     *
     * @var WebhookStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\ReThink\BridgeSDK\Models\Components\WebhookStatus')]
    public WebhookStatus $status;

    /**
     * The public key (in PEM format) that should be used to verify the authenticity of webhook events
     *
     * @var string $publicKey
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('public_key')]
    public string $publicKey;

    /**
     * The list of event categories that the webhook endpoint will receive
     *
     * @var ?array<WebhookEventCategory> $eventCategories
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('event_categories')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\ReThink\BridgeSDK\Models\Components\WebhookEventCategory>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $eventCategories = null;

    /**
     * @param  string  $id
     * @param  string  $url
     * @param  WebhookStatus  $status
     * @param  string  $publicKey
     * @param  ?array<WebhookEventCategory>  $eventCategories
     * @phpstan-pure
     */
    public function __construct(string $id, string $url, WebhookStatus $status, string $publicKey, ?array $eventCategories = null)
    {
        $this->id = $id;
        $this->url = $url;
        $this->status = $status;
        $this->publicKey = $publicKey;
        $this->eventCategories = $eventCategories;
    }
}